import db,{id,now} from '../database.js';import {audit} from './audit-service.js';
const fail=(message,status=422)=>{throw Object.assign(new Error(message),{status});};
const ACTIONS=new Set(['SETTLEMENT','REFUND','PAYOUT_DESTINATION','API_KEY_ROTATION','API_KEY_REVOKE','SPLIT_RELEASE']);
export class ApprovalService{
 async policies(workspaceId){return (await db.all('SELECT * FROM approval_policies WHERE workspace_id=? ORDER BY action_type,minimum_amount DESC',[workspaceId])).map(x=>({...x,approver_roles:JSON.parse(x.approver_roles_json)}));}
 async savePolicy(workspaceId,x,userId){if(!ACTIONS.has(x.action_type)||!Number.isInteger(Number(x.minimum_amount))||Number(x.minimum_amount)<0||!Number.isInteger(Number(x.required_approvers))||Number(x.required_approvers)<1||Number(x.required_approvers)>5)fail('Approval policy tidak valid.');const roles=[...new Set((x.approver_roles||[]).filter(v=>['owner','finance','developer'].includes(v)))];if(!roles.length)fail('Role approver wajib dipilih.');const old=await db.get('SELECT id FROM approval_policies WHERE workspace_id=? AND action_type=? AND minimum_amount=?',[workspaceId,x.action_type,x.minimum_amount]),t=now(),pid=old?.id||id('apol');if(old)await db.run('UPDATE approval_policies SET required_approvers=?,approver_roles_json=?,distinct_requester=?,is_active=?,updated_at=? WHERE id=?',[x.required_approvers,JSON.stringify(roles),Number(x.distinct_requester!==false),Number(x.is_active!==false),t,pid]);else await db.run('INSERT INTO approval_policies (id,workspace_id,action_type,minimum_amount,required_approvers,approver_roles_json,distinct_requester,is_active,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?)',[pid,workspaceId,x.action_type,x.minimum_amount,x.required_approvers,JSON.stringify(roles),Number(x.distinct_requester!==false),1,t,t]);await audit('approval_policy.saved',{actorId:userId,targetType:'approval_policy',targetId:pid,metadata:{action_type:x.action_type}});return db.get('SELECT * FROM approval_policies WHERE id=?',[pid]);}
 async applicable(workspaceId,actionType,amount=0){return db.get('SELECT * FROM approval_policies WHERE workspace_id=? AND action_type=? AND is_active=1 AND minimum_amount<=? ORDER BY minimum_amount DESC LIMIT 1',[workspaceId,actionType,amount]);}
 async request({workspaceId,merchantId=null,actionType,targetType,targetId,amount=0,payload={},requestedBy}){if(!ACTIONS.has(actionType)||!targetType||!targetId)fail('Data approval tidak lengkap.');const existing=await db.get("SELECT * FROM approvals WHERE workspace_id=? AND action_type=? AND target_id=? AND status='PENDING'",[workspaceId,actionType,targetId]);if(existing)return existing;const policy=await this.applicable(workspaceId,actionType,amount);if(!policy)return null;const aid=id('apr');await db.run('INSERT INTO approvals (id,workspace_id,merchant_id,action_type,target_type,target_id,amount,required_approvers,requested_by,payload_json,created_at) VALUES (?,?,?,?,?,?,?,?,?,?,?)',[aid,workspaceId,merchantId,actionType,targetType,targetId,amount,policy.required_approvers,requestedBy,JSON.stringify(payload),now()]);await audit('approval.requested',{actorId:requestedBy,targetType:'approval',targetId:aid,metadata:{action_type:actionType,target_id:targetId,amount}});return db.get('SELECT * FROM approvals WHERE id=?',[aid]);}
 async list(workspaceId){return db.all(`SELECT a.*,r.name requester_name,GROUP_CONCAT(DISTINCT d.name ORDER BY ad.created_at SEPARATOR ', ') approver_names FROM approvals a LEFT JOIN admin_users r ON r.id=a.requested_by LEFT JOIN approval_decisions ad ON ad.approval_id=a.id LEFT JOIN admin_users d ON d.id=ad.decided_by WHERE a.workspace_id=? GROUP BY a.id ORDER BY a.created_at DESC`,[workspaceId]);}
 async decide(workspaceId,approvalId,decision,notes,user){if(!['APPROVED','REJECTED'].includes(decision))fail('Keputusan approval tidak valid.');const a=await db.get("SELECT * FROM approvals WHERE id=? AND workspace_id=? AND status='PENDING'",[approvalId,workspaceId]);if(!a)fail('Approval pending tidak ditemukan.',404);const policy=await this.applicable(workspaceId,a.action_type,a.amount);const roles=JSON.parse(policy?.approver_roles_json||'[]');if(!roles.includes(user.role))fail('Role tidak diizinkan menyetujui tindakan ini.',403);if(policy?.distinct_requester&&a.requested_by===user.user_id)fail('Requester tidak boleh menyetujui permintaannya sendiri.',409);try{await db.run('INSERT INTO approval_decisions (id,approval_id,decided_by,decision,notes,created_at) VALUES (?,?,?,?,?,?)',[id('apd'),a.id,user.user_id,decision,notes||null,now()]);}catch(e){if(e.code==='ER_DUP_ENTRY')fail('Anda sudah memberikan keputusan.',409);throw e;}if(decision==='REJECTED')await db.run("UPDATE approvals SET status='REJECTED',decision_notes=?,decided_at=? WHERE id=?",[notes||null,now(),a.id]);else{const row=await db.get("SELECT COUNT(*) count FROM approval_decisions WHERE approval_id=? AND decision='APPROVED'",[a.id]);await db.run("UPDATE approvals SET approved_count=?,status=IF(? >= required_approvers,'APPROVED','PENDING'),approved_by=IF(? >= required_approvers,?,approved_by),decided_at=IF(? >= required_approvers,?,decided_at) WHERE id=?",[row.count,row.count,row.count,user.user_id,row.count,now(),a.id]);}await audit(`approval.${decision.toLowerCase()}`,{actorId:user.user_id,targetType:'approval',targetId:a.id,metadata:{notes}});return db.get('SELECT * FROM approvals WHERE id=?',[a.id]);}
}
