import crypto from 'node:crypto';import db,{id,now} from '../database.js';
const fail=(m,s=422)=>{throw Object.assign(new Error(m),{status:s})};const hash=v=>crypto.createHash('sha256').update(v).digest('hex');
export class CommerceService{
 customers(merchantId){return db.prepare(`SELECT c.*,COUNT(p.id) payment_count,COALESCE(SUM(CASE WHEN p.status='PAID' THEN p.total_amount ELSE 0 END),0) lifetime_value,MAX(p.created_at) last_payment_at FROM customers c LEFT JOIN payments p ON p.merchant_id=c.merchant_id AND (p.customer_email=c.email OR p.customer_phone=c.phone) WHERE c.merchant_id=? GROUP BY c.id ORDER BY c.updated_at DESC`).all(merchantId)}
 saveCustomer(merchantId,input){if(!input.name?.trim()&&!input.email?.trim()&&!input.phone?.trim())fail('Identitas customer wajib diisi.');const timestamp=now(),customerId=input.id||id('cus');if(input.id){const found=db.prepare('SELECT id FROM customers WHERE id=? AND merchant_id=?').get(input.id,merchantId);if(!found)fail('Customer tidak ditemukan.',404);db.prepare('UPDATE customers SET name=?,email=?,phone=?,notes=?,metadata_json=?,updated_at=? WHERE id=?').run(input.name||null,input.email||null,input.phone||null,input.notes||null,JSON.stringify(input.metadata||{}),timestamp,input.id)}else db.prepare('INSERT INTO customers (id,merchant_id,name,email,phone,notes,metadata_json,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?)').run(customerId,merchantId,input.name||null,input.email||null,input.phone||null,input.notes||null,JSON.stringify(input.metadata||{}),timestamp,timestamp);return db.prepare('SELECT * FROM customers WHERE id=?').get(customerId)}
 invoices(merchantId){return db.prepare('SELECT i.*,c.name customer_name,c.email customer_email FROM invoices i LEFT JOIN customers c ON c.id=i.customer_id WHERE i.merchant_id=? ORDER BY i.created_at DESC').all(merchantId)}
 invoice(invoiceId){const invoice=db.prepare('SELECT i.*,c.name customer_name,c.email customer_email,m.name merchant_name,m.brand_json FROM invoices i LEFT JOIN customers c ON c.id=i.customer_id JOIN merchants m ON m.id=i.merchant_id WHERE i.id=?').get(invoiceId);return invoice?{...invoice,items:db.prepare('SELECT * FROM invoice_items WHERE invoice_id=? ORDER BY position').all(invoiceId)}:null}
 createInvoice(merchantId,input){if(!Array.isArray(input.items)||!input.items.length)fail('Invoice minimal memiliki satu item.');const items=input.items.map((x,n)=>{const quantity=Math.max(1,Number(x.quantity)||1),unit=Number(x.unit_price);if(!x.name?.trim()||!Number.isInteger(unit)||unit<0)fail('Item invoice tidak valid.');return{id:id('itm'),name:x.name.trim(),description:x.description||null,quantity,unit_price:unit,amount:quantity*unit,position:n}});const subtotal=items.reduce((a,x)=>a+x.amount,0),tax=Math.round(subtotal*(Number(input.tax_percent)||0)/100),discount=Math.min(subtotal+tax,Number(input.discount_amount)||0),total=subtotal+tax-discount,timestamp=now(),invoiceId=id('inv'),number=input.number||`INV-${Date.now()}`;db.transaction(()=>{db.prepare('INSERT INTO invoices (id,merchant_id,customer_id,number,status,subtotal,tax_amount,discount_amount,total_amount,due_at,description,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?)').run(invoiceId,merchantId,input.customer_id||null,number,'DRAFT',subtotal,tax,discount,total,input.due_at||null,input.description||null,timestamp,timestamp);const stmt=db.prepare('INSERT INTO invoice_items (id,invoice_id,name,description,quantity,unit_price,amount,position) VALUES (?,?,?,?,?,?,?,?)');for(const x of items)stmt.run(x.id,invoiceId,x.name,x.description,x.quantity,x.unit_price,x.amount,x.position)})();return this.invoice(invoiceId)}
 sendInvoice(invoiceId,jobs){const invoice=this.invoice(invoiceId);if(!invoice)fail('Invoice tidak ditemukan.',404);if(!['DRAFT','OVERDUE'].includes(invoice.status))fail('Invoice tidak dapat dikirim pada status ini.',409);const token=crypto.randomBytes(24).toString('base64url'),timestamp=now();db.prepare("UPDATE invoices SET status='SENT',portal_token_hash=?,sent_at=?,updated_at=? WHERE id=?").run(hash(token),timestamp,timestamp,invoiceId);if(invoice.due_at)jobs.enqueue('invoice.reminder',{invoiceId},invoice.due_at);return{...this.invoice(invoiceId),portal_token:token}}
 portalInvoice(token){const invoice=db.prepare('SELECT id FROM invoices WHERE portal_token_hash=?').get(hash(token));if(!invoice)return null;db.prepare("UPDATE invoices SET viewed_at=COALESCE(viewed_at,?),status=CASE WHEN status='SENT' THEN 'VIEWED' ELSE status END,updated_at=? WHERE id=?").run(now(),now(),invoice.id);return this.invoice(invoice.id)}
 promotions(merchantId){return db.prepare('SELECT * FROM promotions WHERE merchant_id=? OR merchant_id IS NULL ORDER BY created_at DESC').all(merchantId)}
 createPromotion(merchantId,input){if(!input.code?.trim()||!['FIXED','PERCENT'].includes(input.type)||!Number.isInteger(input.value)||input.value<=0)fail('Data promo tidak valid.');const timestamp=now(),promoId=id('pro');db.prepare('INSERT INTO promotions (id,merchant_id,code,type,value,min_amount,max_discount,usage_limit,payment_method,starts_at,ends_at,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?)').run(promoId,merchantId,input.code.trim().toUpperCase(),input.type,input.value,input.min_amount||0,input.max_discount||null,input.usage_limit||null,input.payment_method||null,input.starts_at||null,input.ends_at||null,timestamp,timestamp);return db.prepare('SELECT * FROM promotions WHERE id=?').get(promoId)}
 previewPromotion(merchantId,{code,amount,payment_method}){const p=db.prepare('SELECT * FROM promotions WHERE code=? AND (merchant_id=? OR merchant_id IS NULL) AND is_active=1 ORDER BY merchant_id DESC LIMIT 1').get(String(code||'').toUpperCase(),merchantId);if(!p||amount<p.min_amount||(p.usage_limit&&p.usage_count>=p.usage_limit)||(p.starts_at&&p.starts_at>now())||(p.ends_at&&p.ends_at<now())||(p.payment_method&&p.payment_method!==payment_method))fail('Promo tidak tersedia.',404);let discount=p.type==='PERCENT'?Math.round(amount*p.value/100):p.value;if(p.max_discount)discount=Math.min(discount,p.max_discount);discount=Math.min(discount,amount);return{promotion_id:p.id,discount,total:amount-discount}}
 branding(merchantId,input){if(input){db.prepare('UPDATE merchants SET brand_json=? WHERE id=?').run(JSON.stringify(input),merchantId)}const row=db.prepare('SELECT brand_json FROM merchants WHERE id=?').get(merchantId);return row?.brand_json?JSON.parse(row.brand_json):{}}
}
