import crypto from 'node:crypto';
import nodemailer from 'nodemailer';
import db,{id,now} from '../database.js';
import {config} from '../config.js';
import {encryptSecret,decryptSecret} from './security-service.js';
const hash=value=>crypto.createHash('sha256').update(value).digest('hex');
const alphabet='ABCDEFGHIJKLMNOPQRSTUVWXYZ234567';
const base32=buffer=>{let bits='',out='';for(const byte of buffer)bits+=byte.toString(2).padStart(8,'0');for(let i=0;i<bits.length;i+=5)out+=alphabet[parseInt(bits.slice(i,i+5).padEnd(5,'0'),2)];return out;};
const decode=value=>{let bits='';for(const c of value.replace(/=+$/,'').toUpperCase())bits+=alphabet.indexOf(c).toString(2).padStart(5,'0');return Buffer.from((bits.match(/.{8}/g)||[]).map(x=>parseInt(x,2)));};
const hotp=(secret,counter)=>{const b=Buffer.alloc(8);b.writeBigUInt64BE(BigInt(counter));const h=crypto.createHmac('sha1',decode(secret)).update(b).digest(),o=h[19]&15;return String(((h[o]&127)<<24|(h[o+1]&255)<<16|(h[o+2]&255)<<8|(h[o+3]&255))%1e6).padStart(6,'0');};
const verifyTotp=(secret,code)=>[-1,0,1].some(offset=>{const candidate=hotp(secret,Math.floor(Date.now()/30000)+offset);const a=Buffer.from(candidate),b=Buffer.from(String(code||''));return a.length===b.length&&crypto.timingSafeEqual(a,b);});
export class IdentityService{
 async sendVerification(userId){const user=await db.get('SELECT id,email,name,email_verified_at FROM admin_users WHERE id=?',[userId]);if(!user||user.email_verified_at)return;const token=crypto.randomBytes(32).toString('base64url');await db.run('INSERT INTO identity_tokens (id,user_id,purpose,token_hash,expires_at,created_at) VALUES (?,?,?,?,?,?)',[id('idt'),user.id,'EMAIL_VERIFY',hash(token),new Date(Date.now()+24*3600000).toISOString(),now()]);if(!process.env.SMTP_URL)return;const url=new URL('/?verify='+encodeURIComponent(token),config.baseUrl).toString();await nodemailer.createTransport(process.env.SMTP_URL).sendMail({from:process.env.SMTP_FROM||'EvoPay <no-reply@evopay.local>',to:user.email,subject:'Verifikasi email EvoPay',text:`Halo ${user.name}, verifikasi email Anda dalam 24 jam: ${url}`});}
 async verifyEmail(token){const row=await db.get("SELECT * FROM identity_tokens WHERE purpose='EMAIL_VERIFY' AND token_hash=? AND used_at IS NULL AND expires_at>?",[hash(String(token||'')),now()]);if(!row)throw Object.assign(new Error('Tautan verifikasi tidak valid atau kedaluwarsa.'),{status:422});await db.transaction(async tx=>{await tx.run('UPDATE admin_users SET email_verified_at=? WHERE id=?',[now(),row.user_id]);await tx.run('UPDATE identity_tokens SET used_at=? WHERE id=?',[now(),row.id]);});}
 async beginTotp(userId,email){const secret=base32(crypto.randomBytes(20));await db.run('UPDATE admin_users SET totp_secret_encrypted=?,totp_enabled=0 WHERE id=?',[encryptSecret(secret),userId]);return{secret,otpauth_uri:`otpauth://totp/EvoPay:${encodeURIComponent(email)}?secret=${secret}&issuer=EvoPay&digits=6&period=30`};}
 async enableTotp(userId,code){const user=await db.get('SELECT totp_secret_encrypted FROM admin_users WHERE id=?',[userId]),secret=decryptSecret(user?.totp_secret_encrypted);if(!secret||!verifyTotp(secret,code))throw Object.assign(new Error('Kode authenticator tidak valid.'),{status:422});const codes=Array.from({length:8},()=>crypto.randomBytes(5).toString('hex').toUpperCase());await db.transaction(async tx=>{await tx.run('UPDATE admin_users SET totp_enabled=1 WHERE id=?',[userId]);await tx.run('DELETE FROM recovery_codes WHERE user_id=?',[userId]);for(const code of codes)await tx.run('INSERT INTO recovery_codes (id,user_id,code_hash,created_at) VALUES (?,?,?,?)',[id('rc'),userId,hash(code),now()]);});return codes;}
 async verifySecondFactor(userId,code){const user=await db.get('SELECT totp_enabled,totp_secret_encrypted FROM admin_users WHERE id=?',[userId]);if(user?.totp_enabled&&verifyTotp(decryptSecret(user.totp_secret_encrypted),code))return true;const recovery=await db.get('SELECT id FROM recovery_codes WHERE user_id=? AND code_hash=? AND used_at IS NULL',[userId,hash(String(code||'').toUpperCase())]);if(!recovery)return false;await db.run('UPDATE recovery_codes SET used_at=? WHERE id=?',[now(),recovery.id]);return true;}
 async disableTotp(userId){await db.transaction(async tx=>{await tx.run('UPDATE admin_users SET totp_enabled=0,totp_secret_encrypted=NULL WHERE id=?',[userId]);await tx.run('DELETE FROM recovery_codes WHERE user_id=?',[userId]);});}
 async status(userId){const u=await db.get('SELECT email_verified_at,totp_enabled FROM admin_users WHERE id=?',[userId]);return{email_verified:Boolean(u.email_verified_at),email_verified_at:u.email_verified_at,totp_enabled:Boolean(u.totp_enabled)};}
}
export {verifyTotp};
