import crypto from 'node:crypto';import db,{id,now} from '../database.js';import {assertSafeOutboundUrl} from './outbound-url-policy.js';import {config} from '../config.js';
const fail=(m,s=422)=>{throw Object.assign(new Error(m),{status:s});};
export class NotificationService{
 async create({workspaceId=null,userId=null,eventType,title,body,metadata=null}){const item={id:id('ntf'),user_id:userId,event_type:eventType,title,body,metadata_json:metadata?JSON.stringify(metadata):null,read_at:null,created_at:now()};await db.run('INSERT INTO in_app_notifications (id,user_id,event_type,title,body,metadata_json,read_at,created_at) VALUES (?,?,?,?,?,?,?,?)',Object.values(item));if(workspaceId)await this.dispatch(workspaceId,eventType,{title,body,metadata});return item;}
 async list(userId,{unreadOnly=false,limit=100}={}){return db.all(`SELECT * FROM in_app_notifications WHERE (user_id IS NULL OR user_id=?) ${unreadOnly?'AND read_at IS NULL':''} ORDER BY created_at DESC LIMIT ?`,[userId,Math.min(200,limit)]);}
 async markRead(notificationId,userId){const result=await db.run('UPDATE in_app_notifications SET read_at=? WHERE id=? AND (user_id IS NULL OR user_id=?)',[now(),notificationId,userId]);if(!result.changes)fail('Notifikasi tidak ditemukan.',404);return db.get('SELECT * FROM in_app_notifications WHERE id=?',[notificationId]);}
 async markAllRead(userId){return(await db.run('UPDATE in_app_notifications SET read_at=? WHERE read_at IS NULL AND (user_id IS NULL OR user_id=?)',[now(),userId])).changes;}
 async channels(workspaceId){return db.all('SELECT id,type,name,is_active,created_at,updated_at FROM notification_channels WHERE workspace_id=? ORDER BY created_at DESC',[workspaceId]);}
 async saveChannel(workspaceId,x){if(!['EMAIL','SLACK','TELEGRAM','IN_APP'].includes(x.type)||!x.name?.trim())fail('Channel tidak valid.');const cfg=x.config||{};if(['SLACK','TELEGRAM'].includes(x.type)){if(!cfg.url)fail('URL channel wajib diisi.');await assertSafeOutboundUrl(cfg.url);}if(x.type==='EMAIL'&&!cfg.to?.includes('@'))fail('Email tujuan tidak valid.');const cid=id('nch'),t=now();await db.run('INSERT INTO notification_channels (id,workspace_id,type,name,config_json,created_at,updated_at) VALUES (?,?,?,?,?,?,?)',[cid,workspaceId,x.type,x.name.trim(),JSON.stringify(cfg),t,t]);return{id:cid,type:x.type,name:x.name};}
 async saveRule(workspaceId,x,userId){const supported=['payment.failure_spike','provider.degraded','webhook.dead_letter','settlement.pending','dispute.deadline'];if(!supported.includes(x.event_type)||!Array.isArray(x.channel_ids)||!x.channel_ids.length)fail('Alert rule tidak valid.');const count=(await db.get(`SELECT COUNT(*) count FROM notification_channels WHERE workspace_id=? AND id IN (${x.channel_ids.map(()=>'?').join(',')})`,[workspaceId,...x.channel_ids])).count;if(Number(count)!==new Set(x.channel_ids).size)fail('Channel tidak ditemukan.',404);const rid=id('nrl'),t=now();await db.run('INSERT INTO notification_rules (id,workspace_id,event_type,channel_ids_json,mute_start,mute_end,created_by,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?)',[rid,workspaceId,x.event_type,JSON.stringify(x.channel_ids),x.mute_start||null,x.mute_end||null,userId,t,t]);return db.get('SELECT * FROM notification_rules WHERE id=?',[rid]);}
 muted(rule){if(!rule.mute_start||!rule.mute_end)return false;const current=new Date().toISOString().slice(11,16);return rule.mute_start<=rule.mute_end?current>=rule.mute_start&&current<rule.mute_end:current>=rule.mute_start||current<rule.mute_end;}
 async dispatch(workspaceId,eventType,payload){const rules=await db.all('SELECT * FROM notification_rules WHERE workspace_id=? AND event_type=? AND is_active=1',[workspaceId,eventType]);for(const rule of rules){if(this.muted(rule))continue;for(const channelId of JSON.parse(rule.channel_ids_json)){const channel=await db.get('SELECT * FROM notification_channels WHERE id=? AND workspace_id=? AND is_active=1',[channelId,workspaceId]);if(channel)await this.deliver(channel,eventType,payload);}}}
 async deliver(channel,eventType,payload){const eid=id('nev'),dedup=crypto.createHash('sha256').update(`${channel.id}:${eventType}:${JSON.stringify(payload)}`).digest('hex'),existing=await db.get('SELECT id FROM notification_events WHERE dedup_key=? AND created_at>=?',[dedup,new Date(Date.now()-300000).toISOString()]);if(existing)return existing;await db.run("INSERT INTO notification_events (id,channel_id,event_type,dedup_key,status,payload_json,created_at) VALUES (?,?,?,?,'PENDING',?,?)",[eid,channel.id,eventType,dedup,JSON.stringify(payload),now()]);try{const cfg=JSON.parse(channel.config_json);if(channel.type==='IN_APP'){}else if(channel.type==='EMAIL'){if(!config.smtpUrl)throw new Error('SMTP_URL belum dikonfigurasi.');throw new Error('SMTP adapter belum tersedia.');}else{await assertSafeOutboundUrl(cfg.url);const body=JSON.stringify(channel.type==='SLACK'?{text:`${payload.title}\n${payload.body}`}:{text:`${payload.title}\n${payload.body}`,chat_id:cfg.chat_id});const signature=crypto.createHmac('sha256',config.encryptionKey).update(body).digest('hex'),response=await fetch(cfg.url,{method:'POST',headers:{'content-type':'application/json','x-evopay-signature':signature},body,signal:AbortSignal.timeout(5000)});if(!response.ok)throw Object.assign(new Error(`HTTP ${response.status}`),{responseStatus:response.status});}await db.run("UPDATE notification_events SET status='SENT',attempt_count=attempt_count+1,sent_at=? WHERE id=?",[now(),eid]);}catch(error){await db.run("UPDATE notification_events SET status='RETRYING',attempt_count=attempt_count+1,next_retry_at=?,error=?,response_status=? WHERE id=?",[new Date(Date.now()+60000).toISOString(),error.message,error.responseStatus||null,eid]);}return db.get('SELECT * FROM notification_events WHERE id=?',[eid]);}
 async test(workspaceId,channelId){const channel=await db.get('SELECT * FROM notification_channels WHERE id=? AND workspace_id=?',[channelId,workspaceId]);if(!channel)fail('Channel tidak ditemukan.',404);return this.deliver(channel,'test.notification',{title:'EvoPay test notification',body:'Channel berhasil menerima request pengujian.'});}
}
