import crypto from 'node:crypto';
import db, { id, now } from '../database.js';
const error = (message, status) => Object.assign(new Error(message), { status });
const transitions = { DRAFT: ['SUBMITTED'], SUBMITTED: ['IN_REVIEW', 'REVISION_REQUIRED', 'APPROVED', 'REJECTED'], IN_REVIEW: ['REVISION_REQUIRED', 'APPROVED', 'REJECTED'], REVISION_REQUIRED: ['SUBMITTED'] };
export class OnboardingService {
  get(merchantId) { return db.prepare('SELECT * FROM onboarding_applications WHERE merchant_id=?').get(merchantId) || null; }
  save(merchantId, input) {
    const current = this.get(merchantId); if (current && !['DRAFT','REVISION_REQUIRED'].includes(current.status)) throw error('Aplikasi sedang ditinjau dan tidak dapat diubah.',409);
    const timestamp=now();
    if (!current) db.prepare('INSERT INTO onboarding_applications (id,merchant_id,legal_name,business_type,bank_name,bank_account_last4,bank_owner_name,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?)').run(id('kyc'),merchantId,input.legal_name?.trim(),input.business_type?.trim(),input.bank_name?.trim(),String(input.bank_account_number||'').slice(-4)||null,input.bank_owner_name?.trim(),timestamp,timestamp);
    else db.prepare('UPDATE onboarding_applications SET legal_name=?,business_type=?,bank_name=?,bank_account_last4=?,bank_owner_name=?,revision=revision+1,updated_at=? WHERE id=?').run(input.legal_name?.trim(),input.business_type?.trim(),input.bank_name?.trim(),String(input.bank_account_number||'').slice(-4)||null,input.bank_owner_name?.trim(),timestamp,current.id);
    return this.get(merchantId);
  }
  submit(merchantId) { const app=this.get(merchantId); if(!app||!app.legal_name||!app.business_type||!app.bank_owner_name) throw error('Data legal, jenis usaha, dan pemilik rekening wajib lengkap.',422); this.transition(app,'SUBMITTED'); db.prepare('UPDATE onboarding_applications SET submitted_at=? WHERE id=?').run(now(),app.id); db.prepare('UPDATE merchants SET onboarding_status=? WHERE id=?').run('SUBMITTED',merchantId); return this.get(merchantId); }
  review(applicationId,{status,notes,reviewerId,riskTier='STANDARD',transactionLimit=10000000}) { const app=db.prepare('SELECT * FROM onboarding_applications WHERE id=?').get(applicationId); if(!app) throw error('Aplikasi tidak ditemukan.',404); this.transition(app,status); const timestamp=now(); db.prepare('UPDATE onboarding_applications SET status=?,reviewer_id=?,review_notes=?,risk_tier=?,reviewed_at=?,updated_at=? WHERE id=?').run(status,reviewerId,notes||null,riskTier,timestamp,timestamp,app.id); db.prepare('UPDATE merchants SET onboarding_status=?,risk_tier=?,transaction_limit=? WHERE id=?').run(status,riskTier,transactionLimit,app.merchant_id); return this.get(app.merchant_id); }
  addDocument(applicationId,{document_type,file_name,content}) { const app=db.prepare('SELECT id FROM onboarding_applications WHERE id=?').get(applicationId); if(!app) throw error('Aplikasi tidak ditemukan.',404); if(!document_type||!file_name||!content) throw error('Metadata dan isi dokumen wajib diisi.',422); const checksum=crypto.createHash('sha256').update(String(content)).digest('hex'); const doc={id:id('doc'),applicationId,document_type,file_name,storage_key:`sandbox://${applicationId}/${checksum}`,checksum,created_at:now()}; db.prepare('INSERT INTO kyc_documents (id,application_id,document_type,file_name,storage_key,checksum,created_at) VALUES (?,?,?,?,?,?,?)').run(doc.id,doc.applicationId,doc.document_type,doc.file_name,doc.storage_key,doc.checksum,doc.created_at); return doc; }
  transition(app,next) { if(!(transitions[app.status]||[]).includes(next)) throw error(`Transisi ${app.status} ke ${next} tidak diizinkan.`,409); db.prepare('UPDATE onboarding_applications SET status=?,updated_at=? WHERE id=?').run(next,now(),app.id); }
}
