import crypto from 'node:crypto';
import db,{id,now} from '../database.js';
const fail=(m,s=422)=>{throw Object.assign(new Error(m),{status:s})};

export class OperationsService{
 constructor(routing,providers){this.routing=routing;this.providers=providers}
 async routes(){return db.all('SELECT * FROM provider_route_configs ORDER BY merchant_id,payment_method,priority DESC')}
 async saveRoute(x){
  if(!x.provider||!this.routing.registry.available().includes(x.provider))fail('Provider tidak valid.');
  const t=now(),rid=x.id||id('prc');
  if(x.id)await db.run('UPDATE provider_route_configs SET merchant_id=?,payment_method=?,provider=?,priority=?,weight=?,min_amount=?,max_amount=?,is_active=?,updated_at=? WHERE id=?',[x.merchant_id||null,x.payment_method||null,x.provider,x.priority??100,x.weight??100,x.min_amount||null,x.max_amount||null,Number(x.is_active!==false),t,x.id]);
  else await db.run('INSERT INTO provider_route_configs (id,merchant_id,payment_method,provider,priority,weight,min_amount,max_amount,is_active,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?)',[rid,x.merchant_id||null,x.payment_method||null,x.provider,x.priority??100,x.weight??100,x.min_amount||null,x.max_amount||null,1,t,t]);
  return db.get('SELECT * FROM provider_route_configs WHERE id=?',[rid]);
 }
 async riskRules(workspaceId,merchantId=null){return db.all('SELECT * FROM risk_rules WHERE workspace_id=? AND (merchant_id IS NULL OR merchant_id=?) ORDER BY priority,created_at DESC',[workspaceId,merchantId]);}
 async createRiskRule(x,workspaceId){const signals=['amount','velocity_hour','velocity_day','email_missing','new_customer','ip_velocity_hour','device_velocity_hour','country_mismatch'],operators=['GT','GTE','LT','LTE','EQ','NEQ'],actions=['ALLOW','REVIEW','BLOCK'];if(!x.name?.trim()||!signals.includes(x.signal)||!operators.includes(x.operator)||!actions.includes(x.action)||!Number.isFinite(Number(x.threshold)))fail('Risk rule tidak valid.');const rid=id('rrl');await db.run('INSERT INTO risk_rules (id,workspace_id,merchant_id,name,description,`signal`,`operator`,threshold,window_seconds,score,action,priority,created_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?)',[rid,workspaceId,x.merchant_id||null,x.name.trim(),x.description||null,x.signal,x.operator,Number(x.threshold),x.window_seconds||null,Number(x.score)||0,x.action,Number(x.priority)||100,now()]);return db.get('SELECT * FROM risk_rules WHERE id=?',[rid]);}
 async riskLists(workspaceId,merchantId){return db.all('SELECT id,merchant_id,list_type,subject_type,label,expires_at,created_at FROM risk_lists WHERE workspace_id=? AND (merchant_id IS NULL OR merchant_id=?) AND (expires_at IS NULL OR expires_at>?) ORDER BY created_at DESC',[workspaceId,merchantId,now()]);}
 async addRiskList(x,workspaceId,userId){if(!['ALLOW','BLOCK'].includes(x.list_type)||!['EMAIL','IP','DEVICE','CUSTOMER'].includes(x.subject_type)||!x.value?.trim())fail('Risk list tidak valid.');const hash=crypto.createHash('sha256').update(x.value.trim().toLowerCase()).digest('hex'),rid=id('rls');await db.run('INSERT INTO risk_lists (id,workspace_id,merchant_id,list_type,subject_type,subject_hash,label,expires_at,created_by,created_at) VALUES (?,?,?,?,?,?,?,?,?,?)',[rid,workspaceId,x.merchant_id||null,x.list_type,x.subject_type,hash,x.label||null,x.expires_at||null,userId,now()]);return{id:rid,list_type:x.list_type,subject_type:x.subject_type,label:x.label||null};}
 compare(actual,operator,threshold){return operator==='GT'?actual>threshold:operator==='GTE'?actual>=threshold:operator==='LT'?actual<threshold:operator==='LTE'?actual<=threshold:operator==='EQ'?actual===threshold:actual!==threshold;}
 async riskSignals(merchant,input){const hour=new Date(Date.now()-3600000).toISOString(),day=new Date(Date.now()-86400000).toISOString(),email=input.customer?.email?.trim().toLowerCase(),ip=input.risk?.ip,device=input.risk?.device_id;const [vh,vd,customer]=await Promise.all([db.get('SELECT COUNT(*) count FROM payments WHERE merchant_id=? AND created_at>=?',[merchant.id,hour]),db.get('SELECT COUNT(*) count FROM payments WHERE merchant_id=? AND created_at>=?',[merchant.id,day]),email?db.get("SELECT COUNT(*) count FROM payments WHERE merchant_id=? AND customer_email=?",[merchant.id,email]):{count:0}]);return{amount:Number(input.amount)||0,velocity_hour:Number(vh.count),velocity_day:Number(vd.count),email_missing:email?0:1,new_customer:Number(customer.count)===0?1:0,ip_velocity_hour:Number(input.risk?.ip_velocity_hour)||0,device_velocity_hour:Number(input.risk?.device_velocity_hour)||0,country_mismatch:input.risk?.country_mismatch?1:0,_subjects:{EMAIL:email,IP:ip,DEVICE:device,CUSTOMER:input.customer?.id}};}
 async evaluate(merchant,input,{dryRun=false}={}){const signals=await this.riskSignals(merchant,input),workspaceId=merchant.workspace_id||'ws_legacy_default',rules=(await this.riskRules(workspaceId,merchant.id)).filter(x=>x.is_active),lists=await db.all('SELECT * FROM risk_lists WHERE workspace_id=? AND (merchant_id IS NULL OR merchant_id=?) AND (expires_at IS NULL OR expires_at>?)',[workspaceId,merchant.id,now()]);let listMatch=null;for(const item of lists){const value=signals._subjects[item.subject_type];if(value&&crypto.createHash('sha256').update(String(value).toLowerCase()).digest('hex')===item.subject_hash){listMatch=item;break;}}const matches=rules.filter(r=>this.compare(signals[r.signal],r.operator,Number(r.threshold))),score=matches.reduce((a,x)=>a+x.score,0);let decision=listMatch?.list_type==='ALLOW'?'ALLOW':listMatch?.list_type==='BLOCK'?'BLOCK':matches.some(x=>x.action==='BLOCK')?'BLOCK':matches.some(x=>x.action==='REVIEW')?'REVIEW':'ALLOW';const result={score,decision,signals:{...signals,_subjects:undefined},matches:matches.map(x=>({id:x.id,name:x.name,action:x.action,score:x.score})),list_match:listMatch?{type:listMatch.list_type,subject_type:listMatch.subject_type}:null,dry_run:dryRun};if(dryRun)return result;const eventId=id('rsk');await db.run('INSERT INTO risk_events (id,merchant_id,score,decision,signals_json,review_status,created_at) VALUES (?,?,?,?,?,?,?)',[eventId,merchant.id,score,decision,JSON.stringify(result),decision==='REVIEW'?'PENDING':null,now()]);return{id:eventId,...result};}
 async reviewRisk(eventId,decision,userId){if(!['APPROVED','REJECTED'].includes(decision))fail('Keputusan review tidak valid.');const result=await db.run("UPDATE risk_events SET review_status=?,reviewed_by=? WHERE id=? AND review_status='PENDING'",[decision,userId,eventId]);if(!result.changes)fail('Risk event pending tidak ditemukan.',404);return db.get('SELECT * FROM risk_events WHERE id=?',[eventId]);}
 async disputes(merchantId=null){const where=merchantId?'WHERE p.merchant_id=?':'';return db.all(`SELECT d.*,p.merchant_order_id,p.amount,m.name merchant_name,CASE WHEN d.response_due_at IS NOT NULL AND d.response_due_at<? AND d.status NOT IN ('WON','LOST') THEN 'OVERDUE' WHEN d.response_due_at IS NOT NULL AND d.response_due_at<? AND d.status NOT IN ('WON','LOST') THEN 'DUE_SOON' ELSE d.sla_status END computed_sla FROM disputes d JOIN payments p ON p.id=d.payment_id JOIN merchants m ON m.id=p.merchant_id ${where} ORDER BY COALESCE(d.response_due_at,d.updated_at)`,[...(merchantId?[merchantId]:[]),new Date().toISOString(),new Date(Date.now()+86400000).toISOString()])}
 async dispute(did,merchantId){const d=await db.get('SELECT d.*,p.merchant_order_id,p.amount,m.name merchant_name FROM disputes d JOIN payments p ON p.id=d.payment_id JOIN merchants m ON m.id=p.merchant_id WHERE d.id=? AND p.merchant_id=?',[did,merchantId]);if(!d)fail('Dispute tidak ditemukan.',404);const [timeline,evidence]=await Promise.all([db.all('SELECT e.*,u.name actor_name FROM dispute_events e LEFT JOIN admin_users u ON u.id=e.actor_id WHERE e.dispute_id=? ORDER BY e.created_at',[did]),db.all('SELECT id,type,file_name,storage_key,checksum,checklist_item,status,created_at FROM dispute_evidence WHERE dispute_id=? ORDER BY created_at',[did])]);return{...d,timeline,evidence};}
 async createDispute(x,userId){const p=await db.get("SELECT id,amount FROM payments WHERE id=? AND status='PAID'",[x.payment_id]);if(!p)fail('Pembayaran PAID tidak ditemukan.',404);const amount=Number(x.disputed_amount||p.amount);if(!Number.isInteger(amount)||amount<1||amount>p.amount)fail('Nominal dispute tidak valid.');const due=x.response_due_at?new Date(x.response_due_at):new Date(Date.now()+7*86400000);if(Number.isNaN(due.getTime())||due<=new Date())fail('Deadline dispute harus di masa depan.');const t=now(),did=id('dsp');await db.transaction(async tx=>{await tx.run("INSERT INTO disputes (id,payment_id,status,reason,notes,provider_case_id,reason_code,disputed_amount,response_due_at,assigned_to,response_template,created_at,updated_at) VALUES (?,?,'OPEN',?,?,?,?,?,?,?,?,?,?)",[did,x.payment_id,x.reason||'Customer claim',x.notes||null,x.provider_case_id||null,x.reason_code||'OTHER',amount,due.toISOString(),x.assigned_to||null,x.response_template||null,t,t]);await tx.run("INSERT INTO dispute_events (id,dispute_id,to_status,notes,actor_id,created_at) VALUES (?,?,'OPEN',?,?,?)",[id('dse'),did,JSON.stringify({notes:x.notes||null,deadline:due.toISOString(),amount}),userId,t]);});return db.get('SELECT * FROM disputes WHERE id=?',[did]);}
 async transitionDispute(did,status,notes,userId){const d=await db.get('SELECT * FROM disputes WHERE id=?',[did]),allowed={OPEN:['INVESTIGATING','WON','LOST'],INVESTIGATING:['EVIDENCE_SUBMITTED','WON','LOST'],EVIDENCE_SUBMITTED:['WON','LOST']};if(!d)fail('Dispute tidak ditemukan.',404);if(!allowed[d.status]?.includes(status))fail('Transisi dispute tidak valid.',409);if(status==='EVIDENCE_SUBMITTED'&&!(await db.get('SELECT id FROM dispute_evidence WHERE dispute_id=?',[did])))fail('Minimal satu evidence diperlukan.',409);const t=now();await db.transaction(async tx=>{await tx.run('UPDATE disputes SET status=?,notes=?,sla_status=?,updated_at=? WHERE id=?',[status,notes||d.notes,['WON','LOST'].includes(status)?'CLOSED':d.sla_status,t,did]);await tx.run('INSERT INTO dispute_events (id,dispute_id,from_status,to_status,notes,actor_id,created_at) VALUES (?,?,?,?,?,?,?)',[id('dse'),did,d.status,status,notes||null,userId,t]);});return db.get('SELECT * FROM disputes WHERE id=?',[did]);}
 async addEvidence(did,x,userId){if(!await db.get("SELECT id FROM disputes WHERE id=? AND status IN ('OPEN','INVESTIGATING')",[did]))fail('Dispute tidak ditemukan atau evidence sudah ditutup.',409);if(!x.type||!x.storage_key||!x.checksum||!/^[a-f0-9]{64}$/i.test(x.checksum))fail('Type, storage reference, dan checksum SHA-256 wajib diisi.');if(x.storage_key.startsWith('sandbox://')&&process.env.NODE_ENV==='production')fail('Sandbox evidence tidak tersedia di production.',409);const eid=id('dev');await db.run('INSERT INTO dispute_evidence (id,dispute_id,type,file_name,storage_key,checksum,checklist_item,created_by,created_at) VALUES (?,?,?,?,?,?,?,?,?)',[eid,did,x.type,x.file_name||null,x.storage_key,x.checksum.toLowerCase(),x.checklist_item||null,userId,now()]);await db.run("INSERT INTO dispute_events (id,dispute_id,to_status,notes,actor_id,created_at) SELECT ?,id,status,?,?,? FROM disputes WHERE id=?",[id('dse'),`Evidence ${x.type} ditambahkan`,userId,now(),did]);return db.get('SELECT id,dispute_id,type,file_name,storage_key,checksum,checklist_item,status,created_at FROM dispute_evidence WHERE id=?',[eid]);}
 async assignDispute(did,userId,actorId){const result=await db.run('UPDATE disputes SET assigned_to=?,updated_at=? WHERE id=?',[userId||null,now(),did]);if(!result.changes)fail('Dispute tidak ditemukan.',404);await db.run("INSERT INTO dispute_events (id,dispute_id,to_status,notes,actor_id,created_at) SELECT ?,id,status,?,?,? FROM disputes WHERE id=?",[id('dse'),userId?`Assigned to ${userId}`:'Assignment cleared',actorId,now(),did]);return db.get('SELECT * FROM disputes WHERE id=?',[did]);}
 async dueDisputes(merchantId){return db.all("SELECT d.id,d.response_due_at,d.status,p.merchant_order_id FROM disputes d JOIN payments p ON p.id=d.payment_id WHERE p.merchant_id=? AND d.status NOT IN ('WON','LOST') AND d.response_due_at<=? ORDER BY d.response_due_at",[merchantId,new Date(Date.now()+24*3600000).toISOString()]);}
 async incidents(){
  const incidents=await db.all('SELECT * FROM provider_incidents ORDER BY started_at DESC');
  return Promise.all(incidents.map(async x=>({...x,updates:await db.all('SELECT * FROM incident_updates WHERE incident_id=? ORDER BY created_at',[x.id])})));
 }
 async createIncident(x,userId){
  if(!x.provider||!x.title?.trim()||!['MINOR','MAJOR','CRITICAL'].includes(x.severity))fail('Incident tidak valid.');
  const t=now(),iid=id('inc');
  await db.transaction(async tx=>{
   await tx.run("INSERT INTO provider_incidents (id,provider,title,status,severity,message,started_at,created_at) VALUES (?,?,?,'INVESTIGATING',?,?,?,?)",[iid,x.provider,x.title.trim(),x.severity,x.message||null,t,t]);
   await tx.run("INSERT INTO incident_updates (id,incident_id,status,message,created_by,created_at) VALUES (?,?,'INVESTIGATING',?,?,?)",[id('inu'),iid,x.message||'Investigasi dimulai.',userId,t]);
  });
  await db.run('UPDATE provider_incidents SET public_message=?,affected_methods_json=?,public_status=?,updated_at=? WHERE id=?',[x.public_message||null,JSON.stringify(x.affected_methods||[]),Number(Boolean(x.public_status)),t,iid]);return db.get('SELECT * FROM provider_incidents WHERE id=?',[iid]);
 }
 async updateIncident(iid,x,userId){
  if(!['INVESTIGATING','IDENTIFIED','MONITORING','RESOLVED'].includes(x.status))fail('Status incident tidak valid.');
  const t=now(),result=await db.run('UPDATE provider_incidents SET status=?,message=?,resolved_at=? WHERE id=?',[x.status,x.message||null,x.status==='RESOLVED'?t:null,iid]);
  if(!result.changes)fail('Incident tidak ditemukan.',404);
  await db.run('UPDATE provider_incidents SET public_message=COALESCE(?,public_message),public_status=COALESCE(?,public_status),updated_at=? WHERE id=?',[x.public_message??null,x.public_status==null?null:Number(Boolean(x.public_status)),t,iid]);await db.run('INSERT INTO incident_updates (id,incident_id,status,message,created_by,created_at) VALUES (?,?,?,?,?,?)',[id('inu'),iid,x.status,x.message||x.status,userId,t]);
  return db.get('SELECT * FROM provider_incidents WHERE id=?',[iid]);
 }
 async health(){
  const cutoff=new Date(Date.now()-24*60*60*1000).toISOString();
  const [jobs,payments,providers,openIncidents]=await Promise.all([
   db.all('SELECT status,COUNT(*) count FROM system_jobs GROUP BY status'),
   db.all('SELECT status,COUNT(*) count FROM payments WHERE created_at>=? GROUP BY status',[cutoff]),
   this.providers.summary(),
   db.get("SELECT COUNT(*) count FROM provider_incidents WHERE status!='RESOLVED'")
  ]);
  const degraded=providers.some(x=>!x.configured||x.circuit==='OPEN'||(x.success_rate!=null&&x.success_rate<80));
  return{status:degraded?'DEGRADED':'OPERATIONAL',providers,jobs,payments,open_incidents:openIncidents.count,generated_at:now()};
 }
}
