import crypto from 'node:crypto';import db,{id,now} from '../database.js';const fail=(m,s=422)=>{throw Object.assign(new Error(m),{status:s})};
export class OperationsService{
 constructor(routing,providers){this.routing=routing;this.providers=providers}
 routes(){return db.prepare('SELECT * FROM provider_route_configs ORDER BY merchant_id,payment_method,priority DESC').all()}
 saveRoute(x){if(!x.provider||!this.routing.registry.available().includes(x.provider))fail('Provider tidak valid.');const t=now(),rid=x.id||id('prc');if(x.id)db.prepare('UPDATE provider_route_configs SET merchant_id=?,payment_method=?,provider=?,priority=?,weight=?,min_amount=?,max_amount=?,is_active=?,updated_at=? WHERE id=?').run(x.merchant_id||null,x.payment_method||null,x.provider,x.priority??100,x.weight??100,x.min_amount||null,x.max_amount||null,Number(x.is_active!==false),t,x.id);else db.prepare('INSERT INTO provider_route_configs (id,merchant_id,payment_method,provider,priority,weight,min_amount,max_amount,is_active,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?)').run(rid,x.merchant_id||null,x.payment_method||null,x.provider,x.priority??100,x.weight??100,x.min_amount||null,x.max_amount||null,1,t,t);return db.prepare('SELECT * FROM provider_route_configs WHERE id=?').get(rid)}
 riskRules(){return db.prepare('SELECT * FROM risk_rules ORDER BY created_at DESC').all()}
 createRiskRule(x){if(!x.name?.trim()||!['amount','velocity_hour','email_missing'].includes(x.signal)||!['GT','GTE','EQ'].includes(x.operator)||!['ALLOW','REVIEW','BLOCK'].includes(x.action))fail('Risk rule tidak valid.');const rid=id('rrl');db.prepare('INSERT INTO risk_rules (id,name,signal,operator,threshold,window_seconds,score,action,created_at) VALUES (?,?,?,?,?,?,?,?,?)').run(rid,x.name.trim(),x.signal,x.operator,Number(x.threshold),x.window_seconds||null,x.score||0,x.action,now());return db.prepare('SELECT * FROM risk_rules WHERE id=?').get(rid)}
 evaluate(merchant,input){const velocity=db.prepare("SELECT COUNT(*) count FROM payments WHERE merchant_id=? AND created_at>=datetime('now','-1 hour')").get(merchant.id).count,signals={amount:Number(input.amount)||0,velocity_hour:velocity,email_missing:input.customer?.email?0:1},rules=this.riskRules().filter(x=>x.is_active),matches=rules.filter(r=>r.operator==='GT'?signals[r.signal]>r.threshold:r.operator==='GTE'?signals[r.signal]>=r.threshold:signals[r.signal]===r.threshold),score=matches.reduce((a,x)=>a+x.score,0),decision=matches.some(x=>x.action==='BLOCK')?'BLOCK':matches.some(x=>x.action==='REVIEW')?'REVIEW':'ALLOW',eventId=id('rsk');db.prepare('INSERT INTO risk_events (id,merchant_id,score,decision,signals_json,review_status,created_at) VALUES (?,?,?,?,?,?,?)').run(eventId,merchant.id,score,decision,JSON.stringify({signals,matches:matches.map(x=>x.id)}),decision==='REVIEW'?'PENDING':null,now());return{id:eventId,score,decision,signals}}
 reviewRisk(eventId,decision,userId){if(!['APPROVED','REJECTED'].includes(decision))fail('Keputusan review tidak valid.');const result=db.prepare('UPDATE risk_events SET review_status=?,reviewed_by=? WHERE id=?').run(decision,userId,eventId);if(!result.changes)fail('Risk event tidak ditemukan.',404);return db.prepare('SELECT * FROM risk_events WHERE id=?').get(eventId)}
 disputes(){return db.prepare('SELECT d.*,p.merchant_order_id,p.amount,m.name merchant_name FROM disputes d JOIN payments p ON p.id=d.payment_id JOIN merchants m ON m.id=p.merchant_id ORDER BY d.updated_at DESC').all()}
 createDispute(x,userId){const p=db.prepare("SELECT id FROM payments WHERE id=? AND status='PAID'").get(x.payment_id);if(!p)fail('Pembayaran PAID tidak ditemukan.',404);const t=now(),did=id('dsp');db.transaction(()=>{db.prepare(`INSERT INTO disputes (id,payment_id,status,reason,notes,created_at,updated_at) VALUES (?,?,'OPEN',?,?,?,?)`).run(did,x.payment_id,x.reason||'Customer claim',x.notes||null,t,t);db.prepare(`INSERT INTO dispute_events (id,dispute_id,to_status,notes,actor_id,created_at) VALUES (?,?,'OPEN',?,?,?)`).run(id('dse'),did,x.notes||null,userId,t)})();return db.prepare('SELECT * FROM disputes WHERE id=?').get(did)}
 transitionDispute(did,status,notes,userId){const d=db.prepare('SELECT * FROM disputes WHERE id=?').get(did),allowed={OPEN:['INVESTIGATING','WON','LOST'],INVESTIGATING:['EVIDENCE_SUBMITTED','WON','LOST'],EVIDENCE_SUBMITTED:['WON','LOST']};if(!d)fail('Dispute tidak ditemukan.',404);if(!allowed[d.status]?.includes(status))fail('Transisi dispute tidak valid.',409);const t=now();db.transaction(()=>{db.prepare('UPDATE disputes SET status=?,notes=?,updated_at=? WHERE id=?').run(status,notes||d.notes,t,did);db.prepare('INSERT INTO dispute_events (id,dispute_id,from_status,to_status,notes,actor_id,created_at) VALUES (?,?,?,?,?,?,?)').run(id('dse'),did,d.status,status,notes||null,userId,t)})();return db.prepare('SELECT * FROM disputes WHERE id=?').get(did)}
 addEvidence(did,x,userId){if(!db.prepare('SELECT id FROM disputes WHERE id=?').get(did))fail('Dispute tidak ditemukan.',404);const eid=id('dev'),content=x.content||'',checksum=crypto.createHash('sha256').update(content).digest('hex');db.prepare('INSERT INTO dispute_evidence (id,dispute_id,type,file_name,storage_key,content,checksum,created_by,created_at) VALUES (?,?,?,?,?,?,?,?,?)').run(eid,did,x.type||'NOTE',x.file_name||null,x.storage_key||null,content,checksum,userId,now());return db.prepare('SELECT * FROM dispute_evidence WHERE id=?').get(eid)}
 incidents(){return db.prepare('SELECT * FROM provider_incidents ORDER BY started_at DESC').all().map(x=>({...x,updates:db.prepare('SELECT * FROM incident_updates WHERE incident_id=? ORDER BY created_at').all(x.id)}))}
 createIncident(x,userId){if(!x.provider||!x.title?.trim()||!['MINOR','MAJOR','CRITICAL'].includes(x.severity))fail('Incident tidak valid.');const t=now(),iid=id('inc');db.transaction(()=>{db.prepare(`INSERT INTO provider_incidents (id,provider,title,status,severity,message,started_at,created_at) VALUES (?,?,?,'INVESTIGATING',?,?,?,?)`).run(iid,x.provider,x.title.trim(),x.severity,x.message||null,t,t);db.prepare(`INSERT INTO incident_updates (id,incident_id,status,message,created_by,created_at) VALUES (?,?,'INVESTIGATING',?,?,?)`).run(id('inu'),iid,x.message||'Investigasi dimulai.',userId,t)})();return db.prepare('SELECT * FROM provider_incidents WHERE id=?').get(iid)}
 updateIncident(iid,x,userId){if(!['INVESTIGATING','IDENTIFIED','MONITORING','RESOLVED'].includes(x.status))fail('Status incident tidak valid.');const t=now(),result=db.prepare('UPDATE provider_incidents SET status=?,message=?,resolved_at=? WHERE id=?').run(x.status,x.message||null,x.status==='RESOLVED'?t:null,iid);if(!result.changes)fail('Incident tidak ditemukan.',404);db.prepare('INSERT INTO incident_updates (id,incident_id,status,message,created_by,created_at) VALUES (?,?,?,?,?,?)').run(id('inu'),iid,x.status,x.message||x.status,userId,t);return db.prepare('SELECT * FROM provider_incidents WHERE id=?').get(iid)}
 health(){const jobs=db.prepare("SELECT status,COUNT(*) count FROM system_jobs GROUP BY status").all(),payments=db.prepare("SELECT status,COUNT(*) count FROM payments WHERE created_at>=datetime('now','-24 hour') GROUP BY status").all(),providers=this.providers.summary(),degraded=providers.some(x=>!x.configured||x.circuit==='OPEN'||(x.success_rate!=null&&x.success_rate<80));return{status:degraded?'DEGRADED':'OPERATIONAL',providers,jobs,payments,open_incidents:db.prepare("SELECT COUNT(*) count FROM provider_incidents WHERE status!='RESOLVED'").get().count,generated_at:now()}}
}
