import db,{id,now} from '../database.js';
export class ProviderService{
 constructor(registry){this.registry=registry;}
 async policy(name){let p=await db.get('SELECT * FROM provider_circuit_policies WHERE provider=?',[name]);if(!p){await db.run('INSERT IGNORE INTO provider_circuit_policies (provider,updated_at) VALUES (?,?)',[name,now()]);p=await db.get('SELECT * FROM provider_circuit_policies WHERE provider=?',[name]);}return p;}
 async savePolicy(name,x,userId){if(!this.registry.available().includes(name))throw Object.assign(new Error('Provider tidak valid.'),{status:422});const threshold=Math.min(50,Math.max(1,Number(x.failure_threshold)||5)),recovery=Math.min(3600,Math.max(10,Number(x.recovery_seconds)||60)),samples=Math.min(100,Math.max(1,Number(x.minimum_samples)||5)),rate=Math.min(100,Math.max(1,Number(x.degraded_success_rate)||90));await db.run('INSERT INTO provider_circuit_policies (provider,failure_threshold,recovery_seconds,minimum_samples,degraded_success_rate,updated_by,updated_at) VALUES (?,?,?,?,?,?,?) ON DUPLICATE KEY UPDATE failure_threshold=VALUES(failure_threshold),recovery_seconds=VALUES(recovery_seconds),minimum_samples=VALUES(minimum_samples),degraded_success_rate=VALUES(degraded_success_rate),updated_by=VALUES(updated_by),updated_at=VALUES(updated_at)',[name,threshold,recovery,samples,rate,userId,now()]);return this.policy(name);}
 async record(provider,success,latency,errorClass=null,operation=null,httpStatus=null){await db.run('INSERT INTO provider_metrics(id,provider,success,latency_ms,error_class,operation,http_status,created_at) VALUES(?,?,?,?,?,?,?,?)',[id('met'),provider,success?1:0,Math.round(latency),errorClass,operation,httpStatus,now()]);const p=await this.policy(provider);if(success){if(p.circuit_state==='HALF_OPEN'||p.failure_count)await db.run("UPDATE provider_circuit_policies SET circuit_state='CLOSED',failure_count=0,opened_at=NULL,open_until=NULL,updated_at=? WHERE provider=?",[now(),provider]);}else{const failures=Number(p.failure_count)+1;if(failures>=p.failure_threshold)await db.run("UPDATE provider_circuit_policies SET circuit_state='OPEN',failure_count=?,opened_at=?,open_until=?,updated_at=? WHERE provider=?",[failures,now(),new Date(Date.now()+p.recovery_seconds*1000).toISOString(),now(),provider]);else await db.run('UPDATE provider_circuit_policies SET failure_count=?,updated_at=? WHERE provider=?',[failures,now(),provider]);}}
 async probe(name){const provider=this.registry.get(name),started=Date.now();let success=false,error=null;try{if(!provider.configured())throw new Error('NOT_CONFIGURED');success=true;}catch(caught){error=caught.message;}await this.record(name,success,Date.now()-started,error,'health_probe');await db.run('UPDATE providers SET health_status=?,last_checked_at=? WHERE id=?',[success?'HEALTHY':'DOWN',now(),name]);return{name,success,error};}
 async circuit(name){const p=await this.policy(name);if(p.circuit_state==='OPEN'&&p.open_until&&new Date(p.open_until)<=new Date()){await db.run("UPDATE provider_circuit_policies SET circuit_state='HALF_OPEN',updated_at=? WHERE provider=?",[now(),name]);return{...p,circuit_state:'HALF_OPEN'};}return p;}
 async summary(){const cutoff=new Date(Date.now()-3600000).toISOString();return Promise.all(this.registry.health().map(async item=>{const [m,p]=await Promise.all([db.get('SELECT COUNT(*) total,SUM(success) successes,AVG(latency_ms) latency,SUM(success=0) failures FROM provider_metrics WHERE provider=? AND created_at>=?',[item.name,cutoff]),this.circuit(item.name)]),rate=m.total?Math.round(m.successes/m.total*10000)/100:null,status=p.circuit_state==='OPEN'?'DOWN':m.total>=p.minimum_samples&&rate<p.degraded_success_rate?'DEGRADED':item.configured?'HEALTHY':'DOWN';return{...item,status,success_rate:rate,latency_ms:m.latency?Math.round(m.latency):null,samples:Number(m.total),failures:Number(m.failures||0),circuit_state:p.circuit_state,open_until:p.open_until};}));}
}
