import crypto from 'node:crypto';
import db, { now } from '../database.js';
import { config } from '../config.js';
const b64=(v)=>Buffer.from(v).toString('base64url');
export function encryptSecret(value){if(!value)return null;const iv=crypto.randomBytes(12);const cipher=crypto.createCipheriv('aes-256-gcm',config.encryptionKey,iv);const encrypted=Buffer.concat([cipher.update(String(value),'utf8'),cipher.final()]);return `${b64(iv)}.${b64(cipher.getAuthTag())}.${b64(encrypted)}`}
export function decryptSecret(value){if(!value)return null;const [iv,tag,data]=value.split('.').map(x=>Buffer.from(x,'base64url'));const decipher=crypto.createDecipheriv('aes-256-gcm',config.encryptionKey,iv);decipher.setAuthTag(tag);return Buffer.concat([decipher.update(data),decipher.final()]).toString('utf8')}
export const safeEqual=(a,b)=>{const x=Buffer.from(String(a));const y=Buffer.from(String(b));return x.length===y.length&&crypto.timingSafeEqual(x,y)};
export function canonicalRequest(req,timestamp,nonce){const body=req.rawBody?crypto.createHash('sha256').update(req.rawBody).digest('hex'):crypto.createHash('sha256').update(JSON.stringify(req.body||{})).digest('hex');return `${req.method.toUpperCase()}\n${req.originalUrl.split('?')[0]}\n${timestamp}\n${nonce}\n${body}`}
export async function verifySignedRequest(req,merchant){if(!merchant.require_signature)return {ok:true};const timestamp=req.get('x-nexuspay-timestamp');const nonce=req.get('x-nexuspay-nonce');const signature=req.get('x-nexuspay-signature')?.replace(/^sha256=/,'');if(!timestamp||!nonce||!signature)return {ok:false,message:'Header signature wajib diisi.'};if(Math.abs(Date.now()-Number(timestamp))>300000)return {ok:false,message:'Timestamp request kedaluwarsa.'};const existing=await db.get('SELECT 1 FROM api_nonces WHERE merchant_id=? AND nonce=?',[merchant.id,nonce]);if(existing)return {ok:false,message:'Nonce sudah pernah digunakan.'};const expected=crypto.createHmac('sha256',merchant.webhook_secret||merchant.api_key_hash).update(canonicalRequest(req,timestamp,nonce)).digest('hex');if(!safeEqual(expected,signature))return {ok:false,message:'Signature request tidak valid.'};try{await db.run('INSERT INTO api_nonces (merchant_id,nonce,expires_at) VALUES (?,?,?)',[merchant.id,nonce,new Date(Date.now()+600000).toISOString()])}catch(error){if(error.code==='ER_DUP_ENTRY')return {ok:false,message:'Nonce sudah pernah digunakan.'};throw error}return {ok:true}}
export function isIpAllowed(ip,list){if(!list?.trim())return true;return list.split(',').map(x=>x.trim()).includes(ip)}
export async function pruneSecurityData(){await Promise.all([db.run('DELETE FROM api_nonces WHERE expires_at<?',[now()]),db.run('DELETE FROM admin_sessions WHERE expires_at<?',[now()])])}
