import db, { id, now } from '../database.js';
const DEFAULTS = [['free', 'Free', 0, { payments: 100, credentials: 2 }, { sandbox: true, live: false }], ['growth', 'Growth', 299000, { payments: 5000, credentials: 5 }, { sandbox: true, live: true, analytics: true }], ['business', 'Business', 999000, { payments: 50000, credentials: 20 }, { sandbox: true, live: true, analytics: true, risk: true }], ['enterprise', 'Enterprise', 0, { payments: -1, credentials: -1 }, { sandbox: true, live: true, analytics: true, risk: true, priority_support: true }]];
const view = (row) => row ? { ...row, limits: JSON.parse(row.limits_json), entitlements: JSON.parse(row.entitlements_json) } : null;
export class SubscriptionService {
  async seed() { for (const [planId, name, price, limits, entitlements] of DEFAULTS) await db.run('INSERT IGNORE INTO subscription_plans (id,name,monthly_price,limits_json,entitlements_json,created_at) VALUES (?,?,?,?,?,?)', [planId, name, price, JSON.stringify(limits), JSON.stringify(entitlements), now()]); }
  async plans() { return (await db.all('SELECT * FROM subscription_plans WHERE is_active=1 ORDER BY monthly_price')).map(view); }
  async current(merchantId) { return view(await db.get("SELECT s.*,p.name plan_name,p.limits_json,p.entitlements_json FROM merchant_subscriptions s JOIN subscription_plans p ON p.id=s.plan_id WHERE s.merchant_id=? AND s.status IN ('TRIAL','ACTIVE','GRACE') ORDER BY s.created_at DESC LIMIT 1", [merchantId])); }
  async assign(merchantId, planId, { trialDays = 0, couponCode = null } = {}) { if (!await db.get('SELECT 1 FROM subscription_plans WHERE id=? AND is_active=1', [planId])) throw Object.assign(new Error('Plan tidak ditemukan.'), { status: 404 }); const timestamp = now(); const end = new Date(Date.now() + 30 * 86400000).toISOString(); const trial = trialDays ? new Date(Date.now() + trialDays * 86400000).toISOString() : null; await db.transaction(async (tx) => { await tx.run("UPDATE merchant_subscriptions SET status='CANCELLED',updated_at=? WHERE merchant_id=? AND status IN ('TRIAL','ACTIVE','GRACE')", [timestamp, merchantId]); await tx.run('INSERT INTO merchant_subscriptions (id,merchant_id,plan_id,status,trial_ends_at,current_period_start,current_period_end,coupon_code,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?)', [id('sub'), merchantId, planId, trial ? 'TRIAL' : 'ACTIVE', trial, timestamp, end, couponCode, timestamp, timestamp]); }); return this.current(merchantId); }
  async meter(merchantId, metric, amount = 1) { const period = now().slice(0, 7); await db.run('INSERT INTO usage_counters (merchant_id,metric,period,value,updated_at) VALUES (?,?,?,?,?) ON DUPLICATE KEY UPDATE value=value+VALUES(value),updated_at=VALUES(updated_at)', [merchantId, metric, period, amount, now()]); return (await db.get('SELECT value FROM usage_counters WHERE merchant_id=? AND metric=? AND period=?', [merchantId, metric, period])).value; }
}
