import db,{hashPassword,id,now} from '../database.js';
const ROLES=new Set(['owner','finance','developer','support','viewer']);
const clean=row=>({id:row.id,email:row.email,name:row.name,role:row.role,is_active:Boolean(row.is_active),created_at:row.created_at,last_login_at:row.last_login_at});
const fail=(message,status=422)=>{throw Object.assign(new Error(message),{status})};
export class TeamService{
 async list(){return await db.all('SELECT * FROM admin_users ORDER BY created_at', []).map(clean)}
 invite({email,name,role='viewer',temporaryPassword}){if(!email?.trim()||!name?.trim()||!temporaryPassword||temporaryPassword.length<10)fail('Nama, email, dan password sementara minimal 10 karakter wajib diisi.');if(!ROLES.has(role))fail('Role tidak valid.');const user={id:id('usr'),email:email.trim().toLowerCase(),name:name.trim(),role,created_at:now()};try{db.prepare('INSERT INTO admin_users (id,email,name,password_hash,role,created_at) VALUES (?,?,?,?,?,?)').run(user.id,user.email,user.name,hashPassword(temporaryPassword),user.role,user.created_at)}catch(error){if(error.code?.includes('UNIQUE'))fail('Email sudah terdaftar.',409);throw error}return clean({...user,is_active:1,last_login_at:null})}
 async update(actorId,userId,{role,is_active}){const target=await db.get('SELECT * FROM admin_users WHERE id=?', [userId]);if(!target)fail('Anggota tidak ditemukan.',404);if(target.id===actorId&&is_active===false)fail('Anda tidak dapat menonaktifkan akun sendiri.',409);if(role&&!ROLES.has(role))fail('Role tidak valid.');const nextRole=role||target.role,nextActive=is_active===undefined?target.is_active:Number(Boolean(is_active));if(target.role==='owner'&&(nextRole!=='owner'||!nextActive)){const owners=db.prepare("SELECT COUNT(*) count FROM admin_users WHERE role='owner' AND is_active=1").get().count;if(owners<=1)fail('Workspace harus memiliki minimal satu owner aktif.',409)}await db.run('UPDATE admin_users SET role=?,is_active=? WHERE id=?', [nextRole,nextActive,userId]);if(!nextActive)await db.run('DELETE FROM admin_sessions WHERE user_id=?', [userId]);return clean(await db.get('SELECT * FROM admin_users WHERE id=?', [userId]))}
 async revokeSessions(userId){return await db.run('DELETE FROM admin_sessions WHERE user_id=?', [userId]).changes}
}
