import crypto from 'node:crypto';import db,{id,now} from '../database.js';import {encryptSecret,decryptSecret} from './security-service.js';import {audit} from './audit-service.js';
const fail=(m,s=422)=>{throw Object.assign(new Error(m),{status:s});};const forbidden=/\b(?:\d[ -]*?){13,19}\b|\bcvv\b|\bcvc\b|security.?code/i;
export class VaultService{
 constructor(registry){this.registry=registry;}
 supports(provider){const c=this.registry.get(provider).capabilities?.();return Boolean(c&&typeof c==='object'&&c.tokenization===true);}
 async list(workspaceId,merchantId,customerId,actorId){const rows=await db.all('SELECT id,customer_id,provider,method_type,brand,display_last4,expires_month,expires_year,consent_at,revoked_at,created_at FROM vaulted_payment_methods WHERE workspace_id=? AND merchant_id=? AND customer_id=? ORDER BY created_at DESC',[workspaceId,merchantId,customerId]);await audit('vault.listed',{actorId,targetType:'customer',targetId:customerId,metadata:{merchant_id:merchantId}});return rows;}
 async store(workspaceId,merchantId,x,actorId){const text=JSON.stringify(x);if(forbidden.test(text)||x.pan||x.cvv||x.card_number)fail('PAN, CVV, dan data kartu mentah dilarang.',400);if(!x.customer_id||!x.provider||!x.provider_token?.trim()||!x.consent)fail('Token provider dan consent wajib diisi.');if(!this.supports(x.provider))fail('Provider tidak mendukung tokenization.',409);if(x.provider_token.length>2048)fail('Provider token terlalu panjang.');const fingerprint=crypto.createHash('sha256').update(`${x.provider}:${x.provider_token}`).digest('hex'),vid=id('vlt'),t=now();await db.run('INSERT INTO vaulted_payment_methods (id,workspace_id,merchant_id,customer_id,provider,provider_token_encrypted,token_fingerprint,method_type,brand,display_last4,expires_month,expires_year,consent_at,created_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?)',[vid,workspaceId,merchantId,x.customer_id,x.provider,encryptSecret(x.provider_token),fingerprint,x.method_type||'TOKEN',x.brand||null,x.last4?.slice(-4)||null,x.expires_month||null,x.expires_year||null,t,t]);await audit('vault.method_stored',{actorId,targetType:'vaulted_payment_method',targetId:vid,metadata:{merchant_id:merchantId,provider:x.provider}});return db.get('SELECT id,customer_id,provider,method_type,brand,display_last4,expires_month,expires_year,consent_at,created_at FROM vaulted_payment_methods WHERE id=?',[vid]);}
 async token(workspaceId,merchantId,idValue){const row=await db.get('SELECT * FROM vaulted_payment_methods WHERE id=? AND workspace_id=? AND merchant_id=? AND revoked_at IS NULL',[idValue,workspaceId,merchantId]);if(!row)fail('Saved payment method tidak ditemukan.',404);return{provider:row.provider,token:decryptSecret(row.provider_token_encrypted)};}
 async revoke(workspaceId,merchantId,idValue,actorId){const result=await db.run('UPDATE vaulted_payment_methods SET revoked_at=? WHERE id=? AND workspace_id=? AND merchant_id=? AND revoked_at IS NULL',[now(),idValue,workspaceId,merchantId]);if(!result.changes)fail('Saved payment method tidak ditemukan.',404);await audit('vault.method_revoked',{actorId,targetType:'vaulted_payment_method',targetId:idValue,metadata:{merchant_id:merchantId}});return{id:idValue,revoked:true};}
}
