import mysql from 'mysql2/promise';
import crypto from 'node:crypto';

const pool = mysql.createPool({ host: process.env.DB_HOST || '127.0.0.1', port: Number(process.env.DB_PORT || 3306), user: process.env.DB_USER || 'root', password: process.env.DB_PASSWORD || '', database: process.env.DB_NAME || 'evopay', waitForConnections: true, connectionLimit: 10, charset: 'utf8mb4', timezone: '+00:00' });
const db = {
  async get(sql, params = []) { const [rows] = await pool.execute(sql, params); return rows[0]; },
  async all(sql, params = []) { const [rows] = await pool.execute(sql, params); return rows; },
  async run(sql, params = []) { const [result] = await pool.execute(sql, params); return { changes: result.affectedRows, insertId: result.insertId }; },
  async transaction(fn) { const conn = await pool.getConnection(); try { await conn.beginTransaction(); const tx = { get: async (sql, params = []) => (await conn.execute(sql, params))[0][0], all: async (sql, params = []) => (await conn.execute(sql, params))[0], run: async (sql, params = []) => { const [result] = await conn.execute(sql, params); return { changes: result.affectedRows, insertId: result.insertId }; } }; const result = await fn(tx); await conn.commit(); return result; } catch (error) { await conn.rollback(); throw error; } finally { conn.release(); } },
  close: () => pool.end()
};
export const id = (prefix) => `${prefix}_${crypto.randomBytes(12).toString('hex')}`;
export const now = () => new Date().toISOString();
export const hash = (value) => crypto.createHash('sha256').update(value).digest('hex');
export const hashPassword = (value) => crypto.scryptSync(value, 'evopay-password-v1', 64).toString('hex');
export const verifyPassword = (value, digest) => crypto.timingSafeEqual(Buffer.from(hashPassword(value)), Buffer.from(digest));
export async function initDatabase() {
  const legacy = await db.get("SELECT 1 found FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='payments' AND column_name='merchant_id' LIMIT 1");
  if (legacy) {
    const suffix = new Date().toISOString().slice(0, 10).replaceAll('-', '');
    const archived = await db.get(`SELECT 1 found FROM information_schema.tables WHERE table_schema=DATABASE() AND table_name=?`, [`legacy_payments_${suffix}`]);
    if (!archived) await db.run(`RENAME TABLE payments TO legacy_payments_${suffix}`);
  }
  await db.run(`CREATE TABLE IF NOT EXISTS gateway_admin (id TINYINT PRIMARY KEY, password_hash VARCHAR(128) NOT NULL, created_at VARCHAR(30) NOT NULL, updated_at VARCHAR(30) NOT NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`);
  await db.run(`CREATE TABLE IF NOT EXISTS gateway_sessions (id VARCHAR(64) PRIMARY KEY, token_hash VARCHAR(64) NOT NULL UNIQUE, expires_at VARCHAR(30) NOT NULL, created_at VARCHAR(30) NOT NULL, INDEX idx_gateway_session_expiry (expires_at)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`);
  await db.run(`CREATE TABLE IF NOT EXISTS sites (id VARCHAR(64) PRIMARY KEY, name VARCHAR(120) NOT NULL, api_key_hash VARCHAR(64) NOT NULL UNIQUE, callback_url TEXT NULL, webhook_secret VARCHAR(128) NOT NULL, is_active TINYINT NOT NULL DEFAULT 1, created_at VARCHAR(30) NOT NULL, updated_at VARCHAR(30) NOT NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`);
  await db.run(`CREATE TABLE IF NOT EXISTS payments (id VARCHAR(64) PRIMARY KEY, site_id VARCHAR(64) NOT NULL, order_id VARCHAR(120) NOT NULL, provider_reference VARCHAR(120) NOT NULL UNIQUE, provider_transaction_id VARCHAR(120) NULL, payment_method VARCHAR(50) NOT NULL, amount BIGINT NOT NULL, status VARCHAR(16) NOT NULL, customer_name VARCHAR(120) NULL, customer_email VARCHAR(255) NULL, customer_phone VARCHAR(50) NULL, description TEXT NULL, payment_code VARCHAR(255) NULL, payment_url TEXT NULL, qr_string TEXT NULL, instructions_json JSON NULL, expires_at VARCHAR(30) NULL, paid_at VARCHAR(30) NULL, provider_payload_json JSON NULL, created_at VARCHAR(30) NOT NULL, updated_at VARCHAR(30) NOT NULL, UNIQUE KEY idx_payment_site_order (site_id, order_id), INDEX idx_payment_site_created (site_id, created_at), INDEX idx_payment_status_created (status, created_at), CONSTRAINT fk_payment_site FOREIGN KEY (site_id) REFERENCES sites(id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`);
  await db.run(`CREATE TABLE IF NOT EXISTS payment_events (id VARCHAR(64) PRIMARY KEY, payment_id VARCHAR(64) NULL, type VARCHAR(50) NOT NULL, payload_json JSON NOT NULL, created_at VARCHAR(30) NOT NULL, INDEX idx_payment_event_payment (payment_id, created_at)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`);
  await db.run(`CREATE TABLE IF NOT EXISTS callback_deliveries (id VARCHAR(64) PRIMARY KEY, payment_id VARCHAR(64) NOT NULL, url TEXT NOT NULL, payload_json JSON NOT NULL, signature VARCHAR(128) NOT NULL, status VARCHAR(16) NOT NULL, attempt_count INT NOT NULL DEFAULT 0, next_attempt_at VARCHAR(30) NULL, response_code INT NULL, last_error TEXT NULL, delivered_at VARCHAR(30) NULL, created_at VARCHAR(30) NOT NULL, updated_at VARCHAR(30) NOT NULL, UNIQUE KEY idx_callback_once (payment_id), INDEX idx_callback_due (status, next_attempt_at), CONSTRAINT fk_callback_payment FOREIGN KEY (payment_id) REFERENCES payments(id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`);
  await db.run(`CREATE TABLE IF NOT EXISTS callback_attempts (id VARCHAR(64) PRIMARY KEY, delivery_id VARCHAR(64) NOT NULL, attempt INT NOT NULL, response_code INT NULL, error TEXT NULL, latency_ms INT NOT NULL, created_at VARCHAR(30) NOT NULL, INDEX idx_callback_attempt_delivery (delivery_id, attempt)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`);
  await db.run(`CREATE TABLE IF NOT EXISTS audit_logs (id VARCHAR(64) PRIMARY KEY, action VARCHAR(80) NOT NULL, target_id VARCHAR(64) NULL, metadata_json JSON NULL, created_at VARCHAR(30) NOT NULL, INDEX idx_audit_created (created_at)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`);
  const attemptPreview = await db.get("SELECT 1 found FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='callback_attempts' AND column_name='response_preview' LIMIT 1");
  if (!attemptPreview) await db.run('ALTER TABLE callback_attempts ADD COLUMN response_preview VARCHAR(1024) NULL AFTER error');
  const deliveryLock = await db.get("SELECT 1 found FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='callback_deliveries' AND column_name='locked_at' LIMIT 1");
  if (!deliveryLock) await db.run('ALTER TABLE callback_deliveries ADD COLUMN locked_at VARCHAR(30) NULL AFTER next_attempt_at, ADD INDEX idx_callback_lease (status,next_attempt_at,locked_at)');
  await db.run(`CREATE TABLE IF NOT EXISTS reconciliation_locks (name VARCHAR(32) PRIMARY KEY, locked_at VARCHAR(30) NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`);
  await db.run("INSERT IGNORE INTO reconciliation_locks (name) VALUES ('tokopay')");
  await db.run(`CREATE TABLE IF NOT EXISTS reconciliation_runs (id VARCHAR(64) PRIMARY KEY, trigger_type VARCHAR(10) NOT NULL, status VARCHAR(16) NOT NULL, examined INT NOT NULL DEFAULT 0, matched INT NOT NULL DEFAULT 0, fixed INT NOT NULL DEFAULT 0, errors INT NOT NULL DEFAULT 0, started_at VARCHAR(30) NOT NULL, finished_at VARCHAR(30) NULL, INDEX idx_reconciliation_runs (started_at)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`);
  await db.run(`CREATE TABLE IF NOT EXISTS reconciliation_items (id VARCHAR(64) PRIMARY KEY, run_id VARCHAR(64) NOT NULL, payment_id VARCHAR(64) NOT NULL, before_status VARCHAR(16) NOT NULL, provider_status VARCHAR(16) NULL, after_status VARCHAR(16) NULL, outcome VARCHAR(16) NOT NULL, error VARCHAR(1024) NULL, created_at VARCHAR(30) NOT NULL, INDEX idx_reconciliation_items_run (run_id,created_at), INDEX idx_reconciliation_items_payment (payment_id), CONSTRAINT fk_reconciliation_run FOREIGN KEY (run_id) REFERENCES reconciliation_runs(id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`);
  const auditIndex = await db.get("SELECT 1 found FROM information_schema.statistics WHERE table_schema=DATABASE() AND table_name='audit_logs' AND index_name='idx_audit_action_created' LIMIT 1");
  if (!auditIndex) await db.run('ALTER TABLE audit_logs ADD INDEX idx_audit_action_created (action,created_at)');
  const siteMode = await db.get("SELECT 1 found FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='sites' AND column_name='mode' LIMIT 1");
  if (!siteMode) await db.run("ALTER TABLE sites ADD COLUMN mode VARCHAR(8) NOT NULL DEFAULT 'LIVE' AFTER name, ADD INDEX idx_site_mode (mode)");
  const paymentEnvironment = await db.get("SELECT 1 found FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='payments' AND column_name='environment' LIMIT 1");
  if (!paymentEnvironment) await db.run("ALTER TABLE payments ADD COLUMN environment VARCHAR(8) NOT NULL DEFAULT 'LIVE' AFTER site_id, ADD INDEX idx_payment_environment_status (environment,status)");
  const siteMaintenance = await db.get("SELECT 1 found FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='sites' AND column_name='maintenance_enabled' LIMIT 1");
  if (!siteMaintenance) await db.run("ALTER TABLE sites ADD COLUMN maintenance_enabled TINYINT NOT NULL DEFAULT 0 AFTER is_active, ADD COLUMN maintenance_message VARCHAR(200) NULL AFTER maintenance_enabled, ADD INDEX idx_site_maintenance (is_active,maintenance_enabled)");
  const siteRateLimits = await db.get("SELECT 1 found FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='sites' AND column_name='create_payment_limit_per_minute' LIMIT 1");
  if (!siteRateLimits) await db.run("ALTER TABLE sites ADD COLUMN create_payment_limit_per_minute INT NULL AFTER maintenance_message, ADD COLUMN sync_payment_limit_per_minute INT NULL AFTER create_payment_limit_per_minute");
  await db.run(`CREATE TABLE IF NOT EXISTS site_rate_limit_windows (site_id VARCHAR(64) NOT NULL, bucket VARCHAR(32) NOT NULL, window_start BIGINT NOT NULL, request_count INT NOT NULL, updated_at VARCHAR(30) NOT NULL, PRIMARY KEY (site_id,bucket,window_start), INDEX idx_rate_window (window_start), CONSTRAINT fk_rate_limit_site FOREIGN KEY (site_id) REFERENCES sites(id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`);
  await db.run(`CREATE TABLE IF NOT EXISTS webhook_test_deliveries (id VARCHAR(64) PRIMARY KEY, site_id VARCHAR(64) NOT NULL, url TEXT NOT NULL, payload_json JSON NOT NULL, signature VARCHAR(128) NOT NULL, status VARCHAR(16) NOT NULL, attempt_count INT NOT NULL DEFAULT 0, next_attempt_at VARCHAR(30) NULL, response_code INT NULL, last_error TEXT NULL, created_at VARCHAR(30) NOT NULL, updated_at VARCHAR(30) NOT NULL, INDEX idx_webhook_test_due (status,next_attempt_at), INDEX idx_webhook_test_site (site_id,created_at), CONSTRAINT fk_webhook_test_site FOREIGN KEY (site_id) REFERENCES sites(id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`);
  const testDeliveryLock = await db.get("SELECT 1 found FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='webhook_test_deliveries' AND column_name='locked_at' LIMIT 1");
  if (!testDeliveryLock) await db.run('ALTER TABLE webhook_test_deliveries ADD COLUMN locked_at VARCHAR(30) NULL AFTER next_attempt_at, ADD INDEX idx_webhook_test_lease (status,next_attempt_at,locked_at)');
  await db.run(`CREATE TABLE IF NOT EXISTS webhook_test_attempts (id VARCHAR(64) PRIMARY KEY, delivery_id VARCHAR(64) NOT NULL, attempt INT NOT NULL, response_code INT NULL, error TEXT NULL, response_preview VARCHAR(1024) NULL, latency_ms INT NOT NULL, created_at VARCHAR(30) NOT NULL, INDEX idx_webhook_test_attempt (delivery_id,attempt), CONSTRAINT fk_webhook_test_attempt FOREIGN KEY (delivery_id) REFERENCES webhook_test_deliveries(id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`);
  if (!process.env.ADMIN_PASSWORD) throw new Error('ADMIN_PASSWORD wajib diisi.'); await db.run('INSERT IGNORE INTO gateway_admin (id,password_hash,created_at,updated_at) VALUES (1,?,?,?)', [hashPassword(process.env.ADMIN_PASSWORD), now(), now()]);
}
export default db;
