import 'dotenv/config';
import express from 'express';
import helmet from 'helmet';
import path from 'node:path';
import crypto from 'node:crypto';
import { initDatabase } from './database.js';
import db from './database.js';
import { fileURLToPath } from 'node:url';
import { TokopayProvider } from './providers/tokopay-provider.js';
import { SimulatorProvider } from './providers/simulator-provider.js';
import { ProviderRegistry } from './providers/provider-registry.js';
import { RoutingService } from './services/routing-service.js';
import { ProviderService } from './services/provider-service.js';
import { PaymentService } from './services/payment-service.js';
import { WebhookService } from './services/webhook-service.js';
import paymentRoutes from './routes/payment-routes.js';
import tokopayWebhookRoutes from './routes/tokopay-webhook-routes.js';
import adminRoutes from './routes/admin-routes.js';
import checkoutRoutes from './routes/checkout-routes.js';
import platformRoutes from './routes/platform-routes.js';
import { CredentialService } from './services/credential-service.js';
import { OnboardingService } from './services/onboarding-service.js';
import { SubscriptionService } from './services/subscription-service.js';
import { NotificationService } from './services/notification-service.js';
import { JobService } from './services/job-service.js';
import { TeamService } from './services/team-service.js';
import foundationRoutes from './routes/foundation-routes.js';
import { FinanceService } from './services/finance-service.js';
import financeRoutes from './routes/finance-routes.js';
import { assertProductionConfig, config } from './config.js';
import { PaymentLinkService } from './services/payment-link-service.js';
import commerceRoutes from './routes/commerce-routes.js';
import { CommerceService } from './services/commerce-service.js';
import { BillingFinanceService } from './services/billing-finance-service.js';
import billingFinanceRoutes from './routes/billing-finance-routes.js';
import { OperationsService } from './services/operations-service.js';
import operationsRoutes from './routes/operations-routes.js';
import { DeveloperService } from './services/developer-service.js';
import developerRoutes from './routes/developer-routes.js';
import { GovernanceService } from './services/governance-service.js';
import { ApprovalService } from './services/approval-service.js';
import { SplitPaymentService } from './services/split-payment-service.js';
import { VaultService } from './services/vault-service.js';
import governanceRoutes from './routes/governance-routes.js';
import merchantPortalRoutes from './routes/merchant-portal-routes.js';
import projectFinanceRoutes from './routes/project-finance-routes.js';
import projectCasesRoutes from './routes/project-cases-routes.js';
import projectDeveloperRoutes from './routes/project-developer-routes.js';
import projectCommerceRoutes from './routes/project-commerce-routes.js';
import projectReportsRoutes from './routes/project-reports-routes.js';
import projectOperationsRoutes from './routes/project-operations-routes.js';
import projectRoutingRoutes from './routes/project-routing-routes.js';
import { PayoutDestinationService } from './services/payout-destination-service.js';
import { sameOrigin } from './middleware/admin-security.js';
import { log, metrics, requestObserver } from './observability.js';

assertProductionConfig();
async function bootstrap() {
  await initDatabase();
  const app = express(); const __dirname = path.dirname(fileURLToPath(import.meta.url));
  const tokopay = new TokopayProvider(); const simulator = new SimulatorProvider(); const registry = new ProviderRegistry({ tokopay, simulator }); const routing = new RoutingService(registry); const providerService = new ProviderService(registry); const finance = new FinanceService(); const payoutDestinations = new PayoutDestinationService(); const payments = new PaymentService(routing, finance); const operations = new OperationsService(routing, providerService); // ponytail: MySQL adapter does not support legacy synchronous risk engine yet; re-enable after operations-service is async.
  payments.risk = null; const webhooks = new WebhookService(tokopay, payments); const credentials = new CredentialService(); const developer = new DeveloperService(); const governance = new GovernanceService(); const approvals = new ApprovalService(); const splits = new SplitPaymentService(); const vault = new VaultService(registry); payments.splits=splits; const onboarding = new OnboardingService(); const subscriptions = new SubscriptionService(); const notifications = new NotificationService(); const jobs = new JobService(); const team = new TeamService(); const links = new PaymentLinkService(); const commerce = new CommerceService(); const billingFinance = new BillingFinanceService(payments,vault,links,jobs);
  jobs.register('notification.create', (payload) => notifications.create(payload));
  jobs.register('invoice.reminder', async ({ invoiceId }) => { const invoice = await commerce.invoice(invoiceId); if (invoice && !['PAID', 'CANCELLED'].includes(invoice.status)) await notifications.create({ eventType: 'invoice.reminder', title: `Invoice ${invoice.number} jatuh tempo`, body: `Tagihan ${invoice.customer_name || 'pelanggan'} senilai Rp${invoice.total_amount.toLocaleString('id-ID')} memerlukan tindak lanjut.`, metadata: { invoice_id: invoice.id } }); });
  jobs.register('billing.charge', ({ subscriptionId }) => billingFinance.charge(subscriptionId));
  await subscriptions.seed(); await finance.backfill();
  app.disable('x-powered-by'); if (process.env.TRUST_PROXY === '1') app.set('trust proxy', 1); app.use(helmet({ contentSecurityPolicy: config.production ? { directives: { defaultSrc: ["'self'"], scriptSrc: ["'self'"], styleSrc: ["'self'", 'https://fonts.googleapis.com'], fontSrc: ["'self'", 'https://fonts.gstatic.com'], imgSrc: ["'self'", 'data:'], connectSrc: ["'self'"] } } : false })); app.use((req, res, next) => { req.id = req.get('x-request-id') || crypto.randomUUID(); res.set('x-request-id', req.id); next(); }); app.use(requestObserver); app.use(express.json({ limit: '200kb', verify: (req, res, buf) => { req.rawBody = Buffer.from(buf); } }));
  app.use('/api',(req,res,next)=>{const version=req.path.split('/')[1]||'unknown';res.set('EvoPay-API-Version',version);if(version!=='v1'){res.set('Deprecation','true');res.set('Sunset','Sat, 01 Aug 2027 00:00:00 GMT');res.set('Link','</docs>; rel="deprecation"');}res.on('finish',()=>{void db.run('INSERT INTO api_version_usage (id,merchant_id,api_version,method,path,created_at) VALUES (?,?,?,?,?,?)',[crypto.randomUUID(),req.merchant?.id||null,version,req.method,req.path,new Date().toISOString()]).catch(()=>{});});next();});
  app.get('/openapi.yaml',(req,res)=>res.type('application/yaml').sendFile(path.join(__dirname,'../public/openapi.yaml')));
  app.get('/api/changelog',(req,res)=>res.json({data:[{version:'v1',date:'2026-08-23',changes:['Stable payments API','Idempotency required for payment creation','Signed webhook delivery']}] }));
  app.get('/status',async(req,res)=>{const providers=await providerService.summary(),incidents=(await operations.incidents()).filter(x=>x.public_status);res.json({status:providers.some(x=>x.status==='DOWN')?'major_outage':providers.some(x=>x.status==='DEGRADED')?'degraded':'operational',providers:providers.map(x=>({name:x.name,status:x.status,success_rate:x.success_rate,latency_ms:x.latency_ms})),incidents:incidents.map(x=>({id:x.id,title:x.title,severity:x.severity,status:x.status,message:x.public_message,updated_at:x.updated_at}))});});
  app.get('/health', (req, res) => res.json({ status: 'ok', providers: providerService.summary() }));
  app.get('/health/live', (req, res) => res.json({ status: 'ok' }));
  app.get('/health/ready', async (req, res) => { try { await db.get('SELECT 1'); res.json({ status: 'ready', database: 'ok', providers: providerService.summary() }); } catch { res.status(503).json({ status: 'not_ready', database: 'unavailable' }); } });
  app.get('/metrics', (req, res) => res.type('text/plain; version=0.0.4').send(metrics.render()));
  app.use('/api/v1', paymentRoutes(payments)); app.use('/webhooks', tokopayWebhookRoutes(webhooks)); app.use('/admin/api', sameOrigin, adminRoutes(webhooks, payments)); app.use('/checkout/api', checkoutRoutes(payments)); app.use('/admin/api/platform', sameOrigin, platformRoutes(credentials, onboarding, subscriptions)); app.use('/admin/api/finance', sameOrigin, financeRoutes(finance, approvals)); app.use('/admin/api/foundation', sameOrigin, foundationRoutes(team, notifications, jobs)); app.use('/commerce/api', sameOrigin, commerceRoutes(links, payments, commerce, jobs)); app.use('/admin/api/billing-finance', sameOrigin, billingFinanceRoutes(billingFinance, jobs)); app.use('/operations/api', sameOrigin, operationsRoutes(operations)); app.use('/developer/api', sameOrigin, developerRoutes(developer, credentials, webhooks)); app.use('/governance/api', sameOrigin, governanceRoutes(governance, approvals)); app.use('/admin/api/projects', sameOrigin, merchantPortalRoutes(webhooks)); app.use('/admin/api/project-finance', sameOrigin, projectFinanceRoutes(finance, payoutDestinations, splits)); app.use('/admin/api/project-cases', sameOrigin, projectCasesRoutes(operations)); app.use('/admin/api/project-developer', sameOrigin, projectDeveloperRoutes(credentials, developer, webhooks)); app.use('/admin/api/project-commerce', sameOrigin, projectCommerceRoutes(links, commerce, jobs)); app.use('/admin/api/project-reports', sameOrigin, projectReportsRoutes(finance)); app.use('/admin/api/project-operations', sameOrigin, projectOperationsRoutes(operations)); app.use('/admin/api/project-routing', sameOrigin, projectRoutingRoutes(operations, providerService));
  app.use(express.static(path.join(__dirname, '../public')));
  app.get('/pay/:token', (req, res) => res.sendFile(path.join(__dirname, '../public/checkout.html')));
  app.get('*', (req, res, next) => req.path.startsWith('/api/') || req.path.startsWith('/webhooks/') || req.path.startsWith('/admin/api/') || req.path.startsWith('/checkout/api/') ? next() : res.sendFile(path.join(__dirname, '../public/index.html')));
  app.use((error, req, res, next) => { const malformed = error instanceof SyntaxError && error.status === 400 && 'body' in error; const status = malformed ? 400 : error.status || 502, code = malformed ? 'INVALID_JSON' : error.code || 'GATEWAY_ERROR', message = malformed ? 'Payload JSON tidak valid.' : error.message || 'Terjadi kesalahan pada gateway.'; log('error', 'request_error', { request_id: req.id, method: req.method, path: req.path, status, code, message: error.message }); res.status(status).json({ error: { code, message, request_id: req.id } }); });
  const server = app.listen(Number(process.env.PORT || 3000), () => log('info', 'startup', { base_url: config.baseUrl, port: Number(process.env.PORT || 3000) }));
  const worker = setInterval(() => { Promise.allSettled([webhooks.processDue(), jobs.processDue(), ...registry.available().map((name) => providerService.probe(name))]).then((results) => results.filter((item) => item.status === 'rejected').forEach((item) => console.error(JSON.stringify({ level: 'error', component: 'worker', message: item.reason?.message || String(item.reason) })))); }, config.workerIntervalMs); worker.unref();
  let closing = false; const shutdown = (signal) => { if (closing) return; closing = true; clearInterval(worker); console.log(JSON.stringify({ level: 'info', event: 'shutdown', signal })); const force = setTimeout(() => process.exit(1), 10000); force.unref(); server.close(async () => { try { await db.close(); } finally { clearTimeout(force); } }); }; process.on('SIGTERM', () => shutdown('SIGTERM')); process.on('SIGINT', () => shutdown('SIGINT'));
}
bootstrap().catch((error) => { console.error(JSON.stringify({ level: 'fatal', component: 'startup', message: error.message })); process.exit(1); });
