import 'dotenv/config';
import express from 'express';
import helmet from 'helmet';
import path from 'node:path';
import crypto from 'node:crypto';
import { initDatabase } from './database.js';
import db from './database.js';
import { fileURLToPath } from 'node:url';
import { TokopayProvider } from './providers/tokopay-provider.js';
import { SimulatorProvider } from './providers/simulator-provider.js';
import { ProviderRegistry } from './providers/provider-registry.js';
import { RoutingService } from './services/routing-service.js';
import { ProviderService } from './services/provider-service.js';
import { PaymentService } from './services/payment-service.js';
import { WebhookService } from './services/webhook-service.js';
import paymentRoutes from './routes/payment-routes.js';
import tokopayWebhookRoutes from './routes/tokopay-webhook-routes.js';
import adminRoutes from './routes/admin-routes.js';
import checkoutRoutes from './routes/checkout-routes.js';
import platformRoutes from './routes/platform-routes.js';
import { CredentialService } from './services/credential-service.js';
import { OnboardingService } from './services/onboarding-service.js';
import { SubscriptionService } from './services/subscription-service.js';
import { NotificationService } from './services/notification-service.js';
import { JobService } from './services/job-service.js';
import { TeamService } from './services/team-service.js';
import foundationRoutes from './routes/foundation-routes.js';
import { FinanceService } from './services/finance-service.js';
import financeRoutes from './routes/finance-routes.js';
import { assertProductionConfig, config } from './config.js';
import { PaymentLinkService } from './services/payment-link-service.js';
import commerceRoutes from './routes/commerce-routes.js';
import { CommerceService } from './services/commerce-service.js';
import { BillingFinanceService } from './services/billing-finance-service.js';
import billingFinanceRoutes from './routes/billing-finance-routes.js';
import { OperationsService } from './services/operations-service.js';
import operationsRoutes from './routes/operations-routes.js';
import { DeveloperService } from './services/developer-service.js';
import developerRoutes from './routes/developer-routes.js';
import { GovernanceService } from './services/governance-service.js';
import governanceRoutes from './routes/governance-routes.js';
import { sameOrigin } from './middleware/admin-security.js';

assertProductionConfig();
async function bootstrap() {
  await initDatabase();
  const app = express(); const __dirname = path.dirname(fileURLToPath(import.meta.url));
  const tokopay = new TokopayProvider(); const simulator = new SimulatorProvider(); const registry = new ProviderRegistry({ tokopay, simulator }); const routing = new RoutingService(registry); const providerService = new ProviderService(registry); const finance = new FinanceService(); const payments = new PaymentService(routing, finance); const operations = new OperationsService(routing, providerService); payments.risk = operations; const webhooks = new WebhookService(tokopay, payments); const credentials = new CredentialService(); const developer = new DeveloperService(); const governance = new GovernanceService(); const onboarding = new OnboardingService(); const subscriptions = new SubscriptionService(); const notifications = new NotificationService(); const jobs = new JobService(); const team = new TeamService(); const links = new PaymentLinkService(); const commerce = new CommerceService(); const billingFinance = new BillingFinanceService();
  jobs.register('notification.create', (payload) => notifications.create(payload));
  jobs.register('invoice.reminder', async ({ invoiceId }) => { const invoice = await commerce.invoice(invoiceId); if (invoice && !['PAID', 'CANCELLED'].includes(invoice.status)) await notifications.create({ eventType: 'invoice.reminder', title: `Invoice ${invoice.number} jatuh tempo`, body: `Tagihan ${invoice.customer_name || 'pelanggan'} senilai Rp${invoice.total_amount.toLocaleString('id-ID')} memerlukan tindak lanjut.`, metadata: { invoice_id: invoice.id } }); });
  jobs.register('billing.charge', ({ subscriptionId }) => billingFinance.charge(subscriptionId));
  await subscriptions.seed(); await finance.backfill();
  app.disable('x-powered-by'); if (process.env.TRUST_PROXY === '1') app.set('trust proxy', 1); app.use(helmet({ contentSecurityPolicy: config.production ? { directives: { defaultSrc: ["'self'"], scriptSrc: ["'self'"], styleSrc: ["'self'", 'https://fonts.googleapis.com'], fontSrc: ["'self'", 'https://fonts.gstatic.com'], imgSrc: ["'self'", 'data:'], connectSrc: ["'self'"] } } : false })); app.use((req, res, next) => { req.id = req.get('x-request-id') || crypto.randomUUID(); res.set('x-request-id', req.id); next(); }); app.use(express.json({ limit: '200kb', verify: (req, res, buf) => { req.rawBody = Buffer.from(buf); } }));
  app.get('/health', (req, res) => res.json({ status: 'ok', providers: providerService.summary() }));
  app.get('/health/live', (req, res) => res.json({ status: 'ok' }));
  app.get('/health/ready', async (req, res) => { try { await db.get('SELECT 1'); res.json({ status: 'ready', database: 'ok', providers: providerService.summary() }); } catch { res.status(503).json({ status: 'not_ready', database: 'unavailable' }); } });
  app.use('/api/v1', paymentRoutes(payments)); app.use('/webhooks', tokopayWebhookRoutes(webhooks)); app.use('/admin/api', sameOrigin, adminRoutes(webhooks, payments)); app.use('/checkout/api', checkoutRoutes(payments)); app.use('/admin/api/platform', sameOrigin, platformRoutes(credentials, onboarding, subscriptions)); app.use('/admin/api/finance', sameOrigin, financeRoutes(finance)); app.use('/admin/api/foundation', sameOrigin, foundationRoutes(team, notifications, jobs)); app.use('/commerce/api', sameOrigin, commerceRoutes(links, payments, commerce, jobs)); app.use('/admin/api/billing-finance', sameOrigin, billingFinanceRoutes(billingFinance, jobs)); app.use('/operations/api', sameOrigin, operationsRoutes(operations)); app.use('/developer/api', sameOrigin, developerRoutes(developer, credentials, webhooks)); app.use('/governance/api', sameOrigin, governanceRoutes(governance));
  app.use(express.static(path.join(__dirname, '../public')));
  app.get('/pay/:token', (req, res) => res.sendFile(path.join(__dirname, '../public/checkout.html')));
  app.get('*', (req, res, next) => req.path.startsWith('/api/') || req.path.startsWith('/webhooks/') || req.path.startsWith('/admin/api/') || req.path.startsWith('/checkout/api/') ? next() : res.sendFile(path.join(__dirname, '../public/index.html')));
  app.use((error, req, res, next) => { const malformed = error instanceof SyntaxError && error.status === 400 && 'body' in error; const status = malformed ? 400 : error.status || 502, code = malformed ? 'INVALID_JSON' : error.code || 'GATEWAY_ERROR', message = malformed ? 'Payload JSON tidak valid.' : error.message || 'Terjadi kesalahan pada gateway.'; console.error(JSON.stringify({ level: 'error', request_id: req.id, method: req.method, path: req.path, status, code, message: error.message })); res.status(status).json({ error: { code, message, request_id: req.id } }); });
  const server = app.listen(Number(process.env.PORT || 3000), () => console.log(`NexusPay running at ${config.baseUrl}`));
  const worker = setInterval(() => { Promise.allSettled([webhooks.processDue(), jobs.processDue(), ...registry.available().map((name) => providerService.probe(name))]).then((results) => results.filter((item) => item.status === 'rejected').forEach((item) => console.error(JSON.stringify({ level: 'error', component: 'worker', message: item.reason?.message || String(item.reason) })))); }, config.workerIntervalMs); worker.unref();
  let closing = false; const shutdown = (signal) => { if (closing) return; closing = true; clearInterval(worker); console.log(JSON.stringify({ level: 'info', event: 'shutdown', signal })); const force = setTimeout(() => process.exit(1), 10000); force.unref(); server.close(async () => { try { await db.close(); } finally { clearTimeout(force); } }); }; process.on('SIGTERM', () => shutdown('SIGTERM')); process.on('SIGINT', () => shutdown('SIGINT'));
}
bootstrap().catch((error) => { console.error(JSON.stringify({ level: 'fatal', component: 'startup', message: error.message })); process.exit(1); });
